### ISSUE TITLE
Add support for getting user's posts/comments.

### ISSUE THREAD

**Issue by chriscn** [aliparlakci/bulk-downloader-for-reddit#10]
It would be nice if this script could also get user's posts (images, gifs, text). If this is already possible please provide some documentation.

**Comment by aliparlakci** [comment]
Getting user's posts feature is going to come with v1.1.0. Check out the alpha version here:
https://github.com/aliparlakci/bulk-downloader-for-reddit/releases/tag/v1.1.0-alpha.1

It also exists in master branch.

**Comment by aliparlakci** [comment]
Command is correct. That feature is really new. There are bugs. Can you
provide your CONSOLE_LOG.txt file? And I try to fix it as soon as I can.

**Comment by chriscn** [comment]
My mistake, I hadn't pulled the latest changes. It now works but `py -3` doesn't actually work on my Mac and so I am using `python3` instead. I believe it is standard practice to use `python3` rather than `py -3`. I'll fix that in the README

**Comment by chriscn** [comment]
This is really weird, but this command `python3 script.py ../Archived/ --user searchandrescuewoods --submitted` fails to find any submissions, where in fact the user has.

**Comment by aliparlakci** [comment]
I am working on the release-1.1.0-prerelease-2 as the previous version is so buggy. I should have checked all the modes if there is a bug.

So you can pull the branch "release-1.1.0-prerelease-2" see if it works on there.

**Comment by aliparlakci** [comment]
I run the command you gave, it responded the same. But not because it is a bug, because that user has no submissions script can download. Check the POSTS.json file. You will see all the posts there.
