### ISSUE TITLE
Avoid duplication

### ISSUE THREAD

**Issue by xR4E** [aliparlakci/bulk-downloader-for-reddit#101]
Hi,

nice tool! Is it possible to avoid duplications by either checking if a file is already in folder X or maybe make the user select the time frame to download posts from (like last 7 days or May 24th to May 31st).

EDIT: I see it skips existing files. But it's kinda hard to know when I need to let the software rerun to have a all posts from like an entire week, because it's based on how many posts people make a day and thats not always the same. So I guess a time frame would be better

**Comment by aliparlakci** [comment]
Sorry but I cannot understand the problem. Can you be more specific?

**Comment by jfroebe** [comment]
I think I understand the request - xR4E, please correct me if I'm wrong..

Currently bulk-downloader-for-reddit avoids downloading the duplicate reddit posts by looking for the existence of the downloaded file.  

A solution would be to generate a history file of posts downloaded.  If a reddit post was already downloaded according to the history file, don't download the post.  Of course the history file location and name should be configurable.  

An example of using a history file can be seen in [youtube-dl](https://ytdl-org.github.io/youtube-dl/index.html) --download-archive FILEPATH

**Comment by aliparlakci** [comment]
Are you aware that the feature already exists?

**Comment by jfroebe** [comment]
I am now - head*desk - sorry about that

**Comment by aliparlakci** [comment]
No problem, thanks for pointing out!
