### ISSUE TITLE
Limit with skip

### ISSUE THREAD

**Issue by captenmasin** [aliparlakci/bulk-downloader-for-reddit#107]
So I'm trying to download my saved posts (800) but I can't download all at once as I keep running out of disk space (I'm downloading and then moving to an external HDD)

Is there currently any way to limit the download and set the starting point?

For example I download the first 100 by setting limit: 100, but then for next 100 I'd like to download items 101-200 etc

**Comment by aliparlakci** [comment]
This was what I was going to suggest.

There was --No-Download option but I removed it. I did not thought it would be helpful. I will bring it back in the next release.

Until than, when you see the first posts is being downloaded, just hit Ctrl+C to quit the application. It will behave same as the --No-Download option.

**Comment by aliparlakci** [comment]
--no-download feature added at v1.9.0
