### ISSUE TITLE
Ability to use --downlaoded-posts and --no-dupes across subreddits when downloading subreddit posts (not user posts)

### ISSUE THREAD

**Issue by ymgenesis** [aliparlakci/bulk-downloader-for-reddit#108]
The readme states `--downloaded-posts` skips the same posts in different subreddits, but as it's setup it only does so when downloading user posts, not subreddit posts.

**example**

When I download 20 user posts and skip downloading duplicates using the `--downloaded-posts` and/or `--no-dupes` options, it works well. Posts are downloaded under the user's folder to multiple subreddit subfolders, and one post they make to multiple subs is only downloaded once.

However, when I download 20 posts from a subreddit using `--downloaded-posts` and/or `--no-dupes`, then download another 20 from a different subreddit with the same post (maybe posted by different user, etc.) using `--downloaded-posts` and/or `--no-dupes`, the post is downloaded again.

I've noticed `--no-dupes` doesn't download duplicate posts from the SAME subreddit when downloading subreddit posts, but it doesn't catch posts from other subreddit folders. `--downloaded-posts` index doesn't catch them, as well.

**request**

I could paste a log, but it would just show 2 posts with similar titles, different IDs (ones stored when using --downloaded-posts), same or different user, being downloaded from 2 different subreddits. 

It would be nice if somehow the program could check for duplicates in other downloaded subreddit folders (when downloading subreddit posts, not user posts). It would be amazing if when downloading subreddit posts we could have the same functionality we get with `--downloaded-posts` and `--no-dupes` when downloading user posts.

If not possible, I can continue to check for and remove duplicates in my download folder using `fdupes` after running your script.

**Comment by aliparlakci** [comment]
I understood your problem. I will add this feature in the next release. Thanks for the feedback!

**Comment by ymgenesis** [comment]
> I understood your problem. I will add this feature in the next release. Thanks for the feedback!
Thanks!!

**Comment by aliparlakci** [comment]
Check out the hash branch

**Comment by ymgenesis** [comment]
Just checked it out. Using `--downloaded-posts` with `--no-dupes` seems to do the trick. Using one without the other still seems to result in duplicates. Not exactly sure how they're implemented to get that result.

**Comment by aliparlakci** [comment]
Feature is added to v1.9.0
