### ISSUE TITLE
Feature Request: Docker version

### ISSUE THREAD

**Issue by suckerfish** [aliparlakci/bulk-downloader-for-reddit#118]
Thank you.

**Comment by aliparlakci** [comment]
Can you use this and give feedback? I will merge it accordingly.

**Comment by suckerfish** [comment]
Hello. Yes I got it working. Couple items/questions, though.

1. This app is meant to download media only, then, right? Videos and pics primarily and maybe self posts? Comment chains are out of scope?
2. At least a couple videos (mp4s) are not coming through with audio, while the original post has audio no problem.  Ffmpeg problem?

Thank you!

**Comment by aliparlakci** [comment]
1. Yes, comments are out of scope at the moment.
2. You have to be more specific about soundless videos. Believe me, "*some* posts are not coming through with audio" is no help at all.
But please open a new issue for the second bug.
