### ISSUE TITLE
Create --config option to explicitly specify config.json file to use.

### ISSUE THREAD

**Issue by r-pufky** [aliparlakci/bulk-downloader-for-reddit#122]
Currently bdfr pulls from {HOME}/Bulk downloader for reddit/config.json or a config in the local script directory. This makes usage difficult, especially if you have multiple configs that you use to pull via scripts and cronjobs.

I'd propose a `--config {FILE} option`, which explicitly points to the configuration to load. If it is not found, the program exits. It will also disable loading from local script directory and {HOME}/Bulk downloader for reddit/config.json. This will make running this in scripts and crontabs MUCH easier.

This wouldn't change how the program functions for basic users, and allow power users to easily use multiple configs without jumping through extra hoops.

I can probably put together a pull request if you are okay with it.

**Comment by aliparlakci** [comment]
If you can open a pull request, I can merge it.

**Comment by ymgenesis** [comment]
You could try using `--use-local-config` in the current directory, but make it a link/alias of a config.json file that exists somewhere else on your system. Not sure if that'd work, but Linux does this kind of thing all the time for its system config files and daemons.
