### ISSUE TITLE
Please remove (or make optional) the Press Enter to Continue at end of script

### ISSUE THREAD

**Issue by markjx** [aliparlakci/bulk-downloader-for-reddit#123]
First: Awesome tool! I really like what you've got here.

I want to script this up to update multiple subreddits in parallel, and generally let this be scriptable.

Please remove the "Press enter to quit" at the end of the script. When the program is done executing, it should just stop executing. 

Thanks!

**Comment by aliparlakci** [comment]
It is optional. See [https://github.com/aliparlakci/bulk-downloader-for-reddit#--quit](https://github.com/aliparlakci/bulk-downloader-for-reddit#--quit)
