### ISSUE TITLE
Not downloading some videos

### ISSUE THREAD

**Issue by wixerzp** [aliparlakci/bulk-downloader-for-reddit#129]
I noticed that some videos were missing from the downloads folder - I checked the log files, and one video is not downloaded but is in both POSTS.json and CONSOLE_LOG.txt logs, and another video is not downloaded too, but it is only logged in the POSTS.json file. There are lots of other missing videos too, but I didn't check the logs for them. The missing videos are I did check are hosted on https://v.redd.it, however there are videos hosted on this domain too that are downloaded. What could be the problem?

**Comment by aliparlakci** [comment]
Can you provide POSTS.json, FAILED.json and CONSOLE_LOG.txt file?

**Comment by wixerzp** [comment]
They're very long, and have personal data. Would it be okay if I just provided the parts of the logs that contain the videos I talked about in the original post? Attached below. Well, I can provide the full FAILED.json file though.
[Posts.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/4826773/Posts.txt)
[ConsoleLog.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/4826771/ConsoleLog.txt)
[FAILED.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/4826774/FAILED.txt)

Also, I tried downloading one of these videos individually - and this is the error I got.  You can go the the link to see that the video is indeed up.
[CONSOLE_LOG.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/4826807/CONSOLE_LOG.txt)

**Comment by aliparlakci** [comment]
The issue is most probably due to the characters on the title. I will look
into that ASAP. Thanks for notifying me!
