### ISSUE TITLE
[Errno 54] Connection reset by peer (for gfycat)

### ISSUE THREAD

**Issue by DennisPing** [aliparlakci/bulk-downloader-for-reddit#130]
### System
Python version 3.7.7
Script version 1.9.1

### Issue
When downloading gfycat videos (lets say qty 20), sometimes the download loses connection on a certain gfycat, tries again, and then permanently gets stuck. Restarting the script and running it again will sometimes download the gfycat... but sometimes it will keep on failing. This issue does not occur with images.

I'm able to manually download the gfycat, so the link is still valid.

### Error message thrown in LOG file
```
(12/20) — {reddit data}
{download directory}
{gfycat file name}.mp4
[Errno 54] Connection reset by peer
Trying again

[Errno 54] Connection reset by peer
Trying again
```

It throws two Errno 54 messages before permanently getting stuck.

Upon looking at StackExchange, it seems to be an issue with the client opening too many sockets, so the server (gfycat in this case) shuts you out. I've noticed this error usually occurs with large gfycats (over ~40 MB size).

### Edit
The issue is coming from youtube-dl. When I download an extremely large gfycat with youtube-dl, the download gets stuck and that Errno 54 gets thrown. In the meantime, maybe it's best to add a function to bypass extremely large gfycats.

**Comment by aliparlakci** [comment]
Maybe I should remove the trying again feature as it is clear that gfycat does not want anyone to download their videos.

**Comment by aliparlakci** [comment]
It is removed.
