### ISSUE TITLE
Requirements not found

### ISSUE THREAD

**Issue by JDOTDO** [aliparlakci/bulk-downloader-for-reddit#131]
When I run the command python3 -m pip install -r -requirements.txt, I get this error message:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '-requirements.txt'.

I didn't do anything with the download and it doesn't work. I am on mac.

Thank you!

**Comment by aliparlakci** [comment]
Oh, it should be ` python3 -m pip install -r requirements.txt`. Do not put any dashes before `requirements.txt`. Thanks for pointing out! I changed the README.
