### ISSUE TITLE
Imgur links not downloading

### ISSUE THREAD

**Issue by KatieWebb** [aliparlakci/bulk-downloader-for-reddit#134]
I'm getting the NotADownloadableLinkError for imgur links. I don't see much information about getting imgur files to download. I verified the link do have images.

**Comment by aliparlakci** [comment]
Can you provide the LOG_FILES? You can directly upload here. Please upload one by one instead of zipping it.

**Comment by KatieWebb** [comment]
[CONSOLE_LOG.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/5012143/CONSOLE_LOG.txt)

**Comment by aliparlakci** [comment]
Solved in the latest version.
