### ISSUE TITLE
Recognizing the same source URL to avoid downloading dupes?

### ISSUE THREAD

**Issue by InPlotITrust** [aliparlakci/bulk-downloader-for-reddit#135]
I'm not sure if this is currently built-in or not, I think there's only a check on reddit post duplicate, based on the reddit post url, but not the actual source link.

I'm currently using the tool to download posts that a user has made. A lot of them are duplicates posted to a different subreddit, but the actual source link is the same redgifs link. What's happening atm is it downloads all of them again and again because they are different posts on reddit, resulting in downloading a lot of extra data and having dupes in the folder while the content is actually the same.

I think it would be nice if it checked the source url and if it's already been downloaded it skips it. This saves both time and data, and you don't have to deal with dupe posts in the folder. This is mainly a concern in regards to redgifs posts as they can often be between 10 - 50MB depending on their length.

**Comment by aliparlakci** [comment]
> I'm not sure if this is currently built-in or not

It is and it is written in the README. In the [--no-dupes](https://github.com/aliparlakci/bulk-downloader-for-reddit#--no-dupes) section, it states that

> Skips the same posts in different subreddits. Does not take any parameter.

You have to use `--no-dupes` option. It is disabled by default.

**Comment by InPlotITrust** [comment]
Ah ok, I missed that part, thanks!
