### ISSUE TITLE
Easy way to merge already downloaded audio and video files?

### ISSUE THREAD

**Issue by nascentt** [aliparlakci/bulk-downloader-for-reddit#136]
I've already used bulk downloader for a while but didn't realize the requirement for ffmpeg until now.  Is there an easy way to retro merge the already downloaded files without having to delete them and redownload?

**Comment by aliparlakci** [comment]
Use a custom script with ffmpeg. This is the command that is used to merge video with audio using ffmepg:

 ```python
ffmpeg -i INPUT_AUDIO -i INPUT_VIDEO -c:v copy -c:a aac -strict experimental OUTPUT
```

There is no program to specifically do that, **as far as I know**.

I am closing the issue as it is unrelated.

**Comment by nascentt** [comment]
Appreciate the answer, although I can't actually find any audio files, so it looks like bulk downloader doesn't actually keep them if it can't find ffmpeg?

**Comment by aliparlakci** [comment]
That is also true.
