### ISSUE TITLE
Keep getting WinError 10054 and some video downloads will just get stuck at XMb/XXMb and won't skip.

### ISSUE THREAD

**Issue by StuffonGithub** [aliparlakci/bulk-downloader-for-reddit#137]
Is this a common issue or does this sound like an isolated one in my case? Maybe something with my system messing with it? Looking at the log files, it seems it mostly happens with RedGIFs downloads.

- **[WinError 10054] An existing connection was forcibly closed by the remote host**

Some files will auto-retry a couple times until it will just return "Failed to download the posts, skipping...", sometimes it will complete on the retry, while others will just get stuck "downloading" at XMb/XXMb.

I once tried to leave it overnight to see if it will skip or continue downloading but come morning, it's still on the same file at the same progress.

I usually just close PowerShell and re-run the command. When it comes back to whatever file got stuck during the previous run, it will either skip or complete downloading but will get stuck on another file again.

**Comment by InPlotITrust** [comment]
I have the same issue on a lot of redgifs links.

**Comment by StuffonGithub** [comment]
> EDIT: Just noticed this has been asked before in #115

Ah, users should know to put proper subjects on issues. Anyway, if that's the case, maybe @aliparlakci can implement some sort of workaround? Not sure how hard this will be to implement but I saw a few RedGIFs posts with a bot you can summon that basically reuploads the GIF to a more download friendly host. Kind of like u/VredditDownloader. I just can't find what the actual bot is.

I know that's not the main purpose of this software but it'd be a pretty neat feature considering RedGIFs is becoming the staple NSFW GIF host. I see it being used more than Imgur.
