### ISSUE TITLE
SyntaxError: invalid syntax - line 117

### ISSUE THREAD

**Issue by dlmarston** [aliparlakci/bulk-downloader-for-reddit#138]
~/bulk-downloader-for-reddit$` python3 script.py
  File "script.py", line 117
    print(f"\n({i+1}/{subsLenght})",end=" — ")
                                  ^
SyntaxError: invalid syntax

This is the error I get. The ^ is actually under the second "

**Comment by dlmarston** [comment]
Python 3.5.2 (default, Apr 16 2020, 17:47:17)

i think i've found the issue

**Comment by ifbx** [comment]
> Python 3.5.2 (default, Apr 16 2020, 17:47:17)
> 
> i think i've found the issue

What was the issue? I have the same problem.

**Comment by aliparlakci** [comment]
Use Python version 3.6.5 or higher. Format strings does not work on previous versions.
