### ISSUE TITLE
Remove pyc files 

### ISSUE THREAD

**Issue by singhkpratham** [aliparlakci/bulk-downloader-for-reddit#140]
Used to work in python a while back, so apologies if my memory is rusty.

Just now found this awesome tool. Thanks.

While extracting files, saw it took a while. It was extracting a lot of _.pyc_ files.
When I used to work on Django etc, _pyc_ files were generally put in _gitignore_. 

I would request to do the same.

**Comment by aliparlakci** [comment]
When you run it from the source code, python generates __pychache__ folder. It contains the compiled source code. So, there is no point in sending those files to the repository. You are right until here.

But, when you generate a binary, python compiles the dependencies you used in the project and puts them inside the package. Source code depends on those binaries. Try deleting the .pyc files and run the application. It will not work.
