### ISSUE TITLE
Friends list option for Submitter

### ISSUE THREAD

**Issue by jordanhchin** [aliparlakci/bulk-downloader-for-reddit#146]
It would be nice to have the option to choose your friends list as the 'Submitter' where it downloads everything from your friends list.

**Comment by NutritiousCookie** [comment]
Downloading from /r/friends will do this from the logged in user.

**Comment by Qwerty-Space** [comment]
> Downloading from `--subreddit friends` will do this from the logged in user.

That doesn't work for me
![image](https://user-images.githubusercontent.com/6967592/123660588-b530ce00-d82b-11eb-83c7-11e37f3263a4.png)

**Comment by Serene-Arc** [comment]
You can't use the `--submitted` option without a user. Try it without that option.

**Comment by Qwerty-Space** [comment]
> You can't use the `--submitted` option without a user. Try it without that option.

Same issue.
![image](https://user-images.githubusercontent.com/6967592/123821158-11aaf080-d8f3-11eb-876a-b9d00aaa3a89.png)
