### ISSUE TITLE
Fetched post count does not match the actual number of posts in a subreddit or user profile.

### ISSUE THREAD

**Issue by StuffonGithub** [aliparlakci/bulk-downloader-for-reddit#147]
When I re-run my commands, on some users or subs, the post count shows an incredibly low number. This doesn't happen to all of them though.

Quickly comparing it with the sub/user profile or even in the directory where I had previously downloaded their content easily shows the disparity of the count.

Here's my basic command template:

`--submitted --user **NAME** --sort new --time all --no-dupes --downloaded-posts **DIRECTORY/log.txt** --directory **DIRECTORY/folder**`

**Comment by Symbiomatrix** [comment]
What kind of "low numbers" are you referring to? There's a server set limit of 1k per sub (for each sort order), 250 per user / search. Or are you referring to disparity in individual posts? If I'm not mistaken, the download count doesn't include duplicates or errors depending on settings.
