### ISSUE TITLE
Post titles are not sanitized, can crash downloader.

### ISSUE THREAD

**Issue by HeySteets** [aliparlakci/bulk-downloader-for-reddit#152]
If you specify a subreddit that contains posts with illegal characters in their titles, BDFR doesn't perform any checks or input sanitization and crashes with `OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect`.

Example: `Greatest Hits of the 31st Century: Songs About Dying in Space` would fail because of the colon in the title, which Windows doesn't allow in file paths.

I haven't had a chance to check if this occurs with other special characters like >, <, \, /, or ".

**Comment by karikamiya** [comment]
Can confirm, just crashed for filename too long.

**Comment by cgsmith** [comment]
This is happening in linux as well
