### ISSUE TITLE
Feature Request: Suppress Logs

### ISSUE THREAD

**Issue by redpoptarts** [aliparlakci/bulk-downloader-for-reddit#157]
I do not want a new folder created every time with logs for what I'm downloading. I don't mind seeing it log to the screen, but I have no intention to use the `LOG_FILES` that are created.   Please create an option to not create these log files.

**Comment by Symbiomatrix** [comment]
I'm with you on that. Code wise, a simple workaround is rewriting utils' printToFile, which most / all other modules call by overriding print.
