### ISSUE TITLE
Not downloading slideshows w/ multiple images

### ISSUE THREAD

**Issue by Appchitect** [aliparlakci/bulk-downloader-for-reddit#161]
When trying to download images that are in Reddit's new slideshow gallery view, images are not downloaded. Trying to download from my "Saved" section.

**Comment by Symbiomatrix** [comment]
Correct, as a new format it requires a new downloader module.
The tag structure is fairly simple, find all a.href contained in figure (and possibly ensure that preview.redd.it is in the selected links), apply imgur's album creation logic; however, getting html 500 error on a plain request.
