### ISSUE TITLE
Feature Request: Unsave Duplicates

### ISSUE THREAD

**Issue by LowBurn** [aliparlakci/bulk-downloader-for-reddit#162]
As far as I can tell duplicates are not unsaved [when using --unsave command]. Any way this can be implemented as well?

_Originally posted by @DigiOhhh in https://github.com/aliparlakci/bulk-downloader-for-reddit/issue_comments/658842063_

**Comment by Symbiomatrix** [comment]
Current duplicate detection is somewhere between very bad and nonexistent - basically just a list getting extended with hash codes, not even a set nor permanently stored in any way, that I could tell (see src.utils -> downloadedPosts). Proper duplicate removal requires at minimum a db, possibly with a similarity detection engine for reposts.
