### ISSUE TITLE
Option to download comments?

### ISSUE THREAD

**Issue by 12-Seconds** [aliparlakci/bulk-downloader-for-reddit#166]
An option to download the comments of a post would be great. For example, r/AskReddit is all about the comments, so it would be great if a `--comments` flag was added

**Comment by Symbiomatrix** [comment]
At a glance, it should be a relatively doable feature. Obtaining the comments in praw is basically as easy as list(submission.comments) in the script's download(submissions) loop.
However, there are additional considerations here:

- Comment sort order.
- Limit on number and depth of comments retrieved (there's some "MoreComments" class and replace_more function as stated in https://praw.readthedocs.io/en/latest/tutorials/comments.html#extracting-comments, needs testing though).
- Save & display format. In particular, nesting doesn't translate very well at all to plain text.
- Exceptions during retrieval.

**Comment by FreeGoldRush** [comment]
The reason I installed this was to download the comments.  That's 99.999% of the content in the subreddit I'm interested in.   Is this really not available?

**Comment by Serene-Arc** [comment]
It is not. However, it can be be added for the v2 release coming if you'd still like it? I intend to add it regardless but I can bump it up if it is a wanted feature.

**Comment by 12-Seconds** [comment]
Please do! I'd love to be able to read the comments of downloaded posts

**Comment by Serene-Arc** [comment]
Alright, it's now part of the milestone for version 2. I'll get on it soon

**Comment by Serene-Arc** [comment]
Implemented in v2 beta

**Comment by atomical** [comment]
@Serene-Arc Is it possible to download the comments of a particular user in v2 beta?

**Comment by Serene-Arc** [comment]
Not currently, if this is a feature you'd like, please open another issue so that i can assign myself to it and put it on the list of things to do.
