### ISSUE TITLE
Fails to download URLs with a query string. E.g., https://i.imgur.com/aaaaaaa.png?1

### ISSUE THREAD

**Issue by AwkwardCauliflower** [aliparlakci/bulk-downloader-for-reddit#167]
Reddit users often add a nonsense query string when reposting a URL to a subreddit to avoid the "link already submitted" error. This program seems to reject them.

**Comment by Symbiomatrix** [comment]
The url posted should likely be classified as "direct", and it seems that category extracts the extension using downloaders/downloaderUtils -> getExtension. That function could do with a bit more cleansing:
```
extension = link.split('?')[0].split('.')[-1]
if extension in imageTypes:
    return "." + extension
else: # Not an extension...
```
There are a few other independent extension validations and extractions, same goes for those.

**Comment by AwkwardCauliflower** [comment]
I don't think it's super common on reddit to use hosts that do this, but some hosts serve images that don't even have a filename in the URL, and rely on the query string to locate the image, and then they respond with the appropriate MIME type and binary data. Some servers use the query string to also provide height and width data for rendering an image, and, if not supplied, return a very tiny default size. So, sometimes, you can't just chop off the query string and expect a good URL.

I think the best thing to do would be to request the headers for a URL and inspect the MIME type and then decide if it's an image or video, and then download it, instead of whitelisting a bunch of extensions and expecting every URL to end in them.

**Comment by Serene-Arc** [comment]
This is done automatically in v2 of the BDFR. It can handle parameters if necessary and passes them to the request while stripping them when needed.
