### ISSUE TITLE
Imgur download error again

### ISSUE THREAD

**Issue by Namke** [aliparlakci/bulk-downloader-for-reddit#170]
I have tested and these link seem only work fine in version 1.6-1.7 (where still using Imgur API), but later version wasn't work at all

```
Error logs:
NotADownloadableLinkError: Could not read the page source on https://imgur.com/a/8itF0Gb
```

**Comment by ComradeEcho** [comment]
This is being caused by Imgur's opt-out beta

I was able to fix this by adding `link = link.replace("https://imgur.com","https://imgur.com/beta/disable?redirect=")` at the top of the `getData(link)` function in Imgur.py, but I don't see that as a long-term solution.

**Comment by Namke** [comment]
Hello guys
Kinda stupid question, why imgur API been removed previously? I thought it work well? Tested with old version and it still work flawlessly.

**Comment by ComradeEcho** [comment]
That's a good question that I don't have the answer to 👉 😎 👉

**Comment by EkriirkE** [comment]
> This is being caused by Imgur's opt-out beta

Would changing the cookie line to 
`cookies = {"over18": "1", "postpagebeta" : "0"} `
work the same for you here?  Unless they monitor the referrer link, that redirect just deletes frontpagebetav2 (which wouldn't be set here anyhow) and sets postpagebeta to 0

**Comment by ComradeEcho** [comment]
Okay so I've modified imgur.py to use the imgur API, and It's going really well so far - my main question as a jr jr software developer is: what's the policy regarding API key credentials?

Should each user have to have their own API ID to use this, or should a random API key be included in the program? I'm not sure how this works
