### ISSUE TITLE
Pretty stupid question but is there a way that I can make it so I have two different instances of BDFR exist in my system?

### ISSUE THREAD

**Issue by StuffonGithub** [aliparlakci/bulk-downloader-for-reddit#178]
Discalimer: I'm tech illiterate (like I literally don't know a lick of coding except if I'm following a documentation) so please forgive my stupidity.

So, for some reason, the `--use-local-config` command doesn't work for me so I'm having to manually do the stuff I need to start downloads.

The two conditions I'd need this is when downloading from a {USER} and from a {SUBREDDIT}. The only changes I'm making when switching are just the `--set-filename` and `--set-folderpath` commands (which would be solved by the config.json file if it's only working on my end).

So, a work-around that I've thought of is having essentially two instances of BDFR, one for {USER} and another for {SUBREDDIT} by simply having two different folders in my system. But the problem is that it still applies the changes I make to the folderpath and filename to the whole BDFR thingy no matter what which makes me think there's a central BDFR process somewhere in my system as if I have it installed as opposed to it being contained to only their respective folders like a portable version (which is how I thought this worked in the first place).

So, my simple question is how can I make it so I can have two "versions" of BDFR in my system so that I can run them both without having to change config settings?

I know there may be some other solution but I really don't know shit about how this works. I'm open to these solutions but I can't guarantee I'd be able to understand them. Lol thanks.

**Comment by pxtang** [comment]
The config is in `~/Bulk\ Downloader\ for\ Reddit` folder

**Comment by aliparlakci** [comment]
First of all, I am not perfect when writing documentations. If there is someone to blame, it is me :)

If there is a file named config.json next to the main program, it overrides the config file in your user directory.

--use-local-config just creates a config.json file next to the program.

However, if you are using command prompt or terminal to start the script and still having issues, try starting the script from the working directory where script.py or bulk-downloader-for-reddit file exists.

More explicitly, below example is wrong

```bash
C:\Users\JohnDoe> .\Downloads\bulk-downloader-for-reddit\bulk-downloader-for-reddit.exe
```

while this is correct:

```bash
C:\Users\JohnDoe> cd .\Downloads\bulk-downloader-for-reddit\
C:\Users\JohnDoe> .\bulk-downloader-for-reddit.exe
```

**Comment by StuffonGithub** [comment]
> What happens when you try `--use-local-config`?

Terminal does nothing for a bit then shows the `X:/home/bulk-downloader> _` location thingy again so I can type new commands but based on Ali's reply above, looks like that command is only meant to create the config.json file, which it does.


@aliparlakci Nah, it was actually a good doc, pretty straightforward. I'm probably just too thick or my "issue" is not general enough to warrant further explanation in it.

I do have a config.json file in the root folder of BDFR but it still follows the format that was applied when running `--set-filename` and  `--set-folderpath` from before no matter what's set in the config.json file.

Perhaps it has something to do with how I have BDFR setup? I'll try to layout my directory as well as the command I run below.

So, I have two different folders of BDFR, one for USERS and one for SUBREDDITS. These folders are straight out of the folder that is extracted from the `bulk_downloader_for_reddit-1.9.4-windows.zip` file we download from Github.

So the main directory has all the files as you have uploaded them but I create one subfolder which will contain the .ps1 files I use to run the commands (I'm too lazy to type everything or even copy/paste the commands, lol).

So the directory tree for both basically looks like this (only difference would be the folders' names):
```
[bulk_downloader_for_reddit-1.9.4-windows]
└ [lib]
└ [subreddits]
   └ subredditA.ps1
   └ subredditB.ps1
   └ subredditC.ps1
└ bulk_downloader_for_reddit.exe
└ config.json
└ python38.dll
└ VCRUNTIME140.dll
```

To run the script, I just open a context menu on any .ps1 file then click 'Run with Powershell' and BDFR does its thing.

Each .ps1 file contains only one line of command. (I think that's a limitation of the script or I'm just too stupid to realise a way around it but I'm at over 300 individual .ps1 files now so it may be too late to go back. Lol.)

Anyway, the commands on the .ps1 files are essentially the same except for the USER/SUBREDDIT and download directory:

`..\bulk-downloader-for-reddit.exe --subreddit SUBREDDIT --sort new --time all --no-dupes --downloaded-posts X:\Downloads\Subreddits\LOG.txt --directory X:\Downloads\Subreddits --quit`


I just tried trying to have a config file in each of the subfolders (just to check) and it's still the same. And if I understood you correctly, adding `--use-local-config` in the command ONLY creates the config file, right? So, it's normal for nothing to happen whenever I run a .ps1 file with an additional `--use-local-config` command?

All I want to do is that when I run subredditA.ps1, it will follow:
```
    "filename": "{DATE}_{SUBREDDIT}_{TITLE}_{POSTID}",
    "folderpath": "{SUBREDDIT}"
```

But when I run userA.ps1, it will follow this instead:
```
    "filename": "{DATE}_{REDDITOR}_{TITLE}_{POSTID}",
    "folderpath": "{REDDITOR}"
```
