### ISSUE TITLE
Unable to specify usernames beginning with -

### ISSUE THREAD

**Issue by Soulsuck24** [aliparlakci/bulk-downloader-for-reddit#190]
### Issue
When trying to download from a username beginning with a - such as ` ./script.py --submitted --user -username` the script errors out with `script.py: error: argument --user: expected one argument` This issue does not happen when not the first character. 

### Workaround
As a workaround, substituting the - with %2D will allow the download to go ahead as normal.
` ./script.py --submitted --user %2Dusername`

**Comment by vladdoster** [comment]
Hi @Soulsuck24,

You can do the following:

```sh
[anonymous@~/code/bulk-downloader-for-reddit(develop)]$ python3 script.py --submitted --user=-username
```

**Comment by Soulsuck24** [comment]
It does appear to.

perhaps would be good to mention in the readme that it's needed.
