### ISSUE TITLE
Downloading reddit galleries

### ISSUE THREAD

**Issue by PotatoLord73** [aliparlakci/bulk-downloader-for-reddit#192]
Currently this program skips downloading reddit galleries, is there any way to fix this. I have no coding experience so I don't know what the first step would be.

**Comment by 4DeepThought2** [comment]
Yep, same issue here.  Im tying to disect the code so I can add something quick, but this could take awhile.

**Comment by 4DeepThought2** [comment]
This PR works - https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/174#pullrequestreview-598163499

**Comment by aliparlakci** [comment]
Merged into master.
