### ISSUE TITLE
Feature request: Argument to disable the usage of subfolders

### ISSUE THREAD

**Issue by Sammala** [aliparlakci/bulk-downloader-for-reddit#193]
Hi there,

first off thanks for making this awesome tool!

I think it would be a useful feature to have if you could disable the usage of subfolders. For example, say you want to download the top 10 upvoted images of Paris: `bulk-downloader-for-reddit.exe --search "Paris" --subreddit all --sort top --time all --skip videos gifs self --limit 10 --directory "PATH" --downloaded-posts "PATH\file.txt" --quit`

When you do that, all of the images get put into separate folders if they are from different subreddits, for example "PATH\Europe", "PATH\pics" etc.

So I think it would be useful if one could use a small argument like --nosubdirectories to tell the tool to put all of the images into "PATH" instead of "PATH\{subreddit}".

That's all, have a nice day! :)

**Comment by 4DeepThought2** [comment]
Second this.  As a matter of fact, Im looking right now at editing the scripts to force it to download the exact `--directory` without appending the subreddits name.  Would be really nice feature.

**Comment by Serene-Arc** [comment]
Noted, I'll add the functionality for the v2 rewrite :)

**Comment by aliparlakci** [comment]
This feature already exists. Created subfolders are completely
customizable. You can remove any subfolder if you want.

**Comment by Serene-Arc** [comment]
Oh yes, so it is. For the users asking, use the `--set-folderpath` option (or edit the config file), and set the folder scheme to be blank. That will dump all of the submissions into the one root folder that you specify.
