### ISSUE TITLE
How to add changes from branches?

### ISSUE THREAD

**Issue by PotatoLord73** [aliparlakci/bulk-downloader-for-reddit#194]
I found this branch called cbf4332 that has some change I would like to add but I have no idea how to do that. Sorry in advance I am new to Github and coding in general.

**Comment by vladdoster** [comment]
@PotatoLord73 You should read these two chapters in the official Git book. 

1.  [Git Branching - Branches in a Nutsell](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell)
1. [Git Branching - Remote Branches](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches)

You could also read the program manual page for a particular program named as PROGRAM-NAME, type this at the command line: man PROGRAM-NAME.

This is not an issue with the program and does not warrant opening one.
