### ISSUE TITLE
Not to be rude, but will there be an update soon?

### ISSUE THREAD

**Issue by PotatoLord73** [aliparlakci/bulk-downloader-for-reddit#196]

**Comment by vladdoster** [comment]
Not enough information here to help.

**Comment by Serene-Arc** [comment]
Yes, I am currently working on a full rewrite of the codebase from scratch. The same sites will be supported and the core functionality will be the same, but many of the complimentary features will be extended, changed, or removed depending on what they are. The downloading part from the user's perspective will not change but users using more advanced/niche features will have to wait for the beta.

I can't guarantee a timeframe for when the update will be ready as it's quite extensive and, unlike the current code, it is fully tested. The tests and code are being written from scratch, though a lot of it is working at the moment. It works as a general download but the rest is still being worked on and there are some important modules still missing.

The update is currently hosted on the `refactor` branch of my fork if you want a look but expect a lot of changes. It's not even at alpha stage yet.
