### ISSUE TITLE
MacOSX Issue - gallery.py and Gallery.py are the same file in OSX

### ISSUE THREAD

**Issue by drifter666** [aliparlakci/bulk-downloader-for-reddit#197]
Hey,

Just a heads up that in src/downloaders/ gallery.py and Gallery.py can't be named the same in the project as the files overwrite one another. I just created a new Gallery2.py in src/downloaders/ and copy/pasted the raw text from github and changed the script.py to reference src.downloaders.Gallery2 and everything works fine again. 

This issue is specific to MacOSX since upper and lower case letter are treated the same now. I'm assuming Windows would do the same, but I never tested it on my Windows box.

Easy fix though.

**Comment by PotatoLord73** [comment]
Where did you put the gallery and script files in the program? I am asking because I do not know where to put them to make it work.

**Comment by c2lknt** [comment]
> Where did you put the gallery and script files in the program? I am asking because I do not know where to put them to make it work.

create a new file: 
````
src/downloaders/Gallery2.py 
````
which should contain this content: 

https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/src/downloaders/Gallery.py

and then edit script.py: 

````diff
- from src.downloaders.Gallery import Gallery
+ from src.downloaders.Gallery2 import Gallery
````

**Comment by Serene-Arc** [comment]
This will be fixed in the rewrite coming soon, where the filenames conform to PEP8 and so there shouldn't be a problem in case-insensitive file systems such as Windows or OSX.

**Comment by aliparlakci** [comment]
Fixed
