### ISSUE TITLE
Rename defaultConfigDirectory to .bdfr

### ISSUE THREAD

**Issue by khawajaumarfarooq** [aliparlakci/bulk-downloader-for-reddit#199]
Hi,

Thanks for making a great tool.

Can the `defaultConfigDirectory` be renamed to `.bdfr` from the current value of `Bulk Downloader for Reddit`?

That way, the directory created will be hidden in File view.

This would be very helpful.

**Comment by Serene-Arc** [comment]
As of v2, which is currently still being developed, the configuration directory will be in the standard location depending on your operating system. So in Windows, it will be in AppData; in Linux, .local/config/bdfr; and so on.

**Comment by khawajaumarfarooq** [comment]
Do we know when v2 is likely to be released? I understand that you might not be able to be exact about it.

**Comment by Serene-Arc** [comment]
I'm currently writing integration tests for the command-line and core part of the downloader, though there's a lot of features that still need to be written before I think it'd be ready for a beta. The documentation still needs to be written from scratch as well, but if you want a purely command-line tool, you can find it on the `refactor` branch of my fork of the project. Be aware that it is still being developed though.

I can't give a release timeframe unfortunately. This is a project that I'm doing in my free time so it depends on what happens with my life. The bulk of the work is done, I think, but there's still a lot to be done.

**Comment by Serene-Arc** [comment]
Implemented in v2 branch beta
