### ISSUE TITLE
Crash updating backup file after other exception

### ISSUE THREAD

**Issue by Murnto** [aliparlakci/bulk-downloader-for-reddit#2]
Each call of `updateBackup(BACKUP_FILE,str(i+1),"add")` in `script.py` will never succeed as `jsonFile.add(toBeAdded)` expects `toBeAdded` to be a dict, but it will always be a string.

**Comment by aliparlakci** [comment]
Fixed. Got rid of the BACKUP feature as with some enhancements script can jump to undownloaded files fast.
