### ISSUE TITLE
No module named 'src.downloaders.Gallery'

### ISSUE THREAD

**Issue by deadcode0815** [aliparlakci/bulk-downloader-for-reddit#200]
python.exe .\script.py
Traceback (most recent call last):
  File "C:\Users\deadbeef\Documents\GitHub\bulk-downloader-for-reddit\script.py", line 19, in <module>
    from src.downloaders.Gallery import Gallery
ModuleNotFoundError: No module named 'src.downloaders.Gallery'

**Comment by bad-jacob** [comment]
This is likely because there is two Gallery.py files in the downloader folder. To work on (case insensitive) windows again one will need to be renamed.

**Comment by aliparlakci** [comment]
Fixed
