### ISSUE TITLE
Specify exact versions of pip packages in requirements.txt

### ISSUE THREAD

**Issue by aliparlakci** [aliparlakci/bulk-downloader-for-reddit#206]
The exact versions of the packages which BDfR works properly should. At least, the major version should be constant for every package to avoid breaking changes.

**Comment by Serene-Arc** [comment]
Why is this necessary? This is generally only done where there are incompatible versions or version-specific features used. Neither of those are the case here. None of them have breaking changes pushed regularly, since Beautiful Soup is packaged by version number. For things like youtube-dl, regular updates are essential to the package working.

**Comment by aliparlakci** [comment]
It is not generally only done where there are incompatible versions or version-specific features used. This is not the case at all.

First of all, you cannot be sure if there won't be any breaking changes to one of the dependencies. Sometimes a bug fix migth be a breaking change and it might affect the BDfR as well.

Second, let's say someone implemented a new functionality using a new feature from a fresh release of one of those packages. Their program will work because they are using the new version of the package. But others who still use the older will see errors. Actually, there were an issues about it yesterday. I suggest checking it out. #205 

It is about specifiying the exact packages, in other words the environment, which BDfR is assured to work. So we don't have to deal with the issues related to dependencies. If we were generating builds and no one was using source code to use the program, then your point *migth* make sense. But now, we are not generating builds after number of changes.

Also, dependency versions should be incremented if the change (new feature, bug fixes etc.) in the dependency is **acknowledged** and it is aggreed that BDfR needs the update. Otherwise, there is no point in using the latest version if the current one is working well.


I suggest fixing the major and minor versions and let patch version increment. See detailed information here [https://semver.org/#spec-item-6](https://semver.org/#spec-item-6)
