### ISSUE TITLE
Delete duplicate files that many not have the same name.

### ISSUE THREAD

**Issue by yaxarat** [aliparlakci/bulk-downloader-for-reddit#208]
When downloading a mass amount of files, inevitably there will be some identical files with different names. This is taxing on the storage so I usually run a personal script that finds and deletes these files. Is there a plan for a built-in feature like this so this process can be automated for those who desire it?

**Comment by aliparlakci** [comment]
It can keep a hash table to smartly understand if a file already exists. Is this why you closed the issue?

**Comment by Serene-Arc** [comment]
This feature already exists with the `--search-existing` and `--no-dupes` options, or alternatively the `--make-hard-links` option.
