### ISSUE TITLE
Error 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by st-korn** [aliparlakci/bulk-downloader-for-reddit#214]
It got an error "'NoneType' object is not iterable".
If you try to get all saved or all liked posts, and where are any one post, removed by moderator.
For example https://www.reddit.com/gallery/lmevyc
![image](https://user-images.githubusercontent.com/26076593/112542534-bc2be880-8dc5-11eb-9054-00ef1aaea816.png)

**Comment by aliparlakci** [comment]
I have checked the pull request. Could you provide a reddit posts which this is an issue and another one which this is not so that I can test it myself?

**Comment by aliparlakci** [comment]
@st-korn
