### ISSUE TITLE
Fails to start after latest git pull

### ISSUE THREAD

**Issue by develroo** [aliparlakci/bulk-downloader-for-reddit#226]
So I just pulled the latest git to rebuild it and setup `config.json` in ~/Bulk Downloader for Reddit but trying to run it give me an error?

```
ERROR:root:KeyError
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/cx_Freeze/initscripts/__startup__.py", line 74, in run
    module.run()
  File "/usr/local/lib/python3.9/dist-packages/cx_Freeze/initscripts/Console.py", line 36, in run
    exec(code, m.__dict__)
  File "script.py", line 374, in <module>
  File "script.py", line 273, in main
KeyError: 'options'

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/cx_Freeze/initscripts/__startup__.py", line 74, in run
    module.run()
  File "/usr/local/lib/python3.9/dist-packages/cx_Freeze/initscripts/Console.py", line 36, in run
    exec(code, m.__dict__)
  File "script.py", line 387, in <module>
AttributeError: 'NoneType' object has no attribute 'quit'

```

 I am on Linux Debian 10 and installed all the requirements via pip3 and it  should be v1.9.4
 
 The config.json is this:
 ```

 {
    "credentials": {
        "reddit_username": "reddituser",
        "reddit": "<APP-KEY>"
    },
    "filename": "{REDDITOR}_{TITLE}_{POSTID}",
    "folderpath": "{SUBREDDIT}",
    "options": "--no-dupes -d  .\"
}
```
How to go about debuggin this?

**Comment by aliparlakci** [comment]
You can checkout to 1 or 2 commits before until the issue is resolved.

**Comment by develroo** [comment]
Source code. I checedkout 1.9.3 and now it complains it cannot read `config.json` Hmm Did the format change or something ?

**Comment by aliparlakci** [comment]
Can you checkout to this commit and try again? #fdff30

**Comment by develroo** [comment]
Hmm nope. Same error. Cannot read config file.  I move the config file and regenerated it and it works. However when I do a diff of the old config and the working one apart from  the options I am see that the working file is not terminated by a newline?

```
diff  config.work config.orig 
8,9c8,9
<     "options": ""
< }
\ No newline at end of file
---
>     "options": "--no-dupes -d  .\ "
> }

```

Could that be related? Is it somehow unable to process newlines when reading json files?

**Comment by DanielBrett** [comment]
Hi guys,

I am not sure if this should be a unique issue or not but my errors are very similar so the source of the issue may be the same.  I followed the instructions [here](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/INTERPRET_FROM_SOURCE.md) but when I try to run I get the following errors.
'''
ERROR:root:KeyError
Traceback (most recent call last):
  File "script.py", line 374, in <module>
    main()
  File "script.py", line 273, in main
    sys.argv = sys.argv + GLOBAL.config["options"].split()
KeyError: 'options'

Traceback (most recent call last):
  File "script.py", line 387, in <module>
    if not GLOBAL.arguments.quit:
AttributeError: 'NoneType' object has no attribute 'quit'
'''

Happy to help in any way I can.  If this is not the right place for this let me know and I'll delete my post and make a new issue.

Thanks,

Daniel

**Comment by cgsmith** [comment]
I receive this error as well when trying to run in docker.

**Comment by cgsmith** [comment]
```
Creating bulk-downloader-for-reddit_bdfr_run ... done
ERROR:root:KeyError
Traceback (most recent call last):
  File "/bdfr/script.py", line 374, in <module>
    main()
  File "/bdfr/script.py", line 273, in main
    sys.argv = sys.argv + GLOBAL.config["options"].split()
KeyError: 'options'

Traceback (most recent call last):
  File "/bdfr/script.py", line 387, in <module>
    if not GLOBAL.arguments.quit:
AttributeError: 'NoneType' object has no attribute 'quit'
ERROR: 1
```

**Comment by aliparlakci** [comment]
Fixed
