### ISSUE TITLE
Doesn't see recent posts?

### ISSUE THREAD

**Issue by nascentt** [aliparlakci/bulk-downloader-for-reddit#232]
Been using this app a few months and loving it, however recently if I run it on a sub it only sees old posts and everything is "already exists" if I browse to the sub I see dozens of new posts, but the tool only seems to see old posts?

**Comment by aliparlakci** [comment]
You have to provide more information on this in order for us to find the issue (if there is any).

**Comment by nascentt** [comment]
I just figured out what was happening.  The sort is defaulted to hot so it downloads those first not the newest.  If I --sort new I get what I was expecting to happen.
Apologies.

(Thank you for the incredible app)
