### ISSUE TITLE
Optimize tests so that they can be run on a CI provider for every commit

### ISSUE THREAD

**Issue by aliparlakci** [aliparlakci/bulk-downloader-for-reddit#238]
Some of the test cases heavily depend on requests to outer sources and consumes too much bandwidth which creates a bottleneck in the test process. Especially reddit takes too long to respond to the requests. They should optimized in order to add CI steps to repository.

This is a general issue which test optimization pull requests can give reference to.

**Comment by Serene-Arc** [comment]
For some test cases that might be possible to do, but it's also the reason that I included the marks system. You can exclude all tests that contact external resources, or tests that contact Reddit, or tests that require an authentication token, or any permutation of them all.

**Comment by Serene-Arc** [comment]
To clarify, it will *never* be possible to run every test with a CI provider. Some tests run for a long time regardless, and some require an authentication token that can't really be provided in this kind of environment. We can run most tests however.
