### ISSUE TITLE
Multiple folders in --folder-scheme does not work

### ISSUE THREAD

**Issue by aliparlakci** [aliparlakci/bulk-downloader-for-reddit#248]
If a path with multiple folder is given such as `--folder-scheme "{REDDITOR}/{SUBREDDIT}"`, all the posts are downloaded to a folder named `{REDDITOR}{SUBREDDIT}`.

For example, a post on r/DataHoarder by aliparlakci will be saved to `~/DataHoarderaliparlakci` instead of `~/DataHoarder/aliparlakci`

Steps to reproduce:
- Run `python3 -m bulkredditdownloader download ./new_folder/ --user anthonyhui --submitted --folder-scheme "{REDDITOR}/{SUBREDDIT}"`

**Comment by aliparlakci** [comment]
Slashes are removed in the below line in bulkredditdownloader/file_name_formatter.py causes the issue:
```python
@staticmethod
def _format_name(submission: (Comment, Submission), format_string: str) -> str:
    if isinstance(submission, Submission):
        attributes = FileNameFormatter._generate_name_dict_from_submission(submission)
    elif isinstance(submission, Comment):
        attributes = FileNameFormatter._generate_name_dict_from_comment(submission)
    else:
        raise BulkDownloaderException(f'Cannot name object {type(submission).__name__}')
    result = format_string
    for key in attributes.keys():
        if re.search(r'(?i).*{{{}}}.*'.format(key), result):
            result = re.sub(r'(?i){{{}}}'.format(key), str(attributes.get(key, 'unknown')), result)
            logger.log(9, f'Found key string {key} in name')

    result = result.replace('/', '') # This line causes the issue

    if platform.system() == 'Windows':
        result = FileNameFormatter._format_for_windows(result)

    return result
```

**Comment by Serene-Arc** [comment]
Yes, slashes are removed because they A. mean different things depending on the operating system, and B. are unwanted in file names and both file and folder schemes clean with the same functions. It shouldn't be *too* hard to fix this I think
