### ISSUE TITLE
V2: Add optional downloader for generic links

### ISSUE THREAD

**Issue by BlipRanger** [aliparlakci/bulk-downloader-for-reddit#249]
I was thinking it might be interesting to have a simple generic downloader for anything not covered by the current selection of downloaders in order to help combat link-rot. After some testing, I've already noticed that some of the saved posts I've archived link to pages that no longer exist. This downloader could utilize the requests library to at least just pull the html or possibly create a warc (web archive) file (using something like [this](https://github.com/webrecorder/warcio)). I understand that this is possibly not desired by all users, so it should probably be optional. If this is within scope, I can start testing out some ways to do this.

**Comment by Serene-Arc** [comment]
My view is that broad archiving like this is better left to other tools. Archiving literally every single resource attached to the page is already done by better tools written by smarter people than me. Things like HTTrack and similar crawlers grab the javascript, images, CSS, and everything necessary to make a faithful reproduction of the site in question. I do not believe that it would be worth implementing all of that when the product would certainly be lesser than what a dedicated crawler could do.

As a compromise, my suggestion would be to parse the logging output for all URLs that failed to download and pass these to a crawler to use and download separately. The following bash command would work well:
```bash
cat log_output.txt | grep -i 'no downloader module exists' | awk '{ print $(NF) }'  
```

**Comment by BlipRanger** [comment]
Works for me, just wanted to put it on the table! Thanks!

**Comment by aliparlakci** [comment]
Quick comment, React and other web frameworks dominating the web more and more every day. If a site runs on React, Vue or Angular, site needs the javascript to construct its content. Downloading only the html source would get you nothing more than a couple of meta tags and a script tag. You will most probably see an empty page when you open the .html file in a browser (assuming javascript is taken down, which is the case)

**Comment by BlipRanger** [comment]
> Quick comment, React and other web frameworks dominating the web more and more every day. If a site runs on React, Vue or Angular, site needs the javascript to construct its content. Downloading only the html source would get you nothing more than a couple of meta tags and a script tag. You will most probably see an empty page when you open the .html file in a browser (assuming javascript is taken down, which is the case here)

Of course, yeah. Stuff like Webrecorder and some other archiving projects are able to capture the javascript, request/response headers, etc. I figured that even just grabbing the skeleton of a page might be worth something (sorta like readability mode on many browsers). But yes, I'll likely be looking into something to call [pywb](https://pywb.readthedocs.io/en/latest/index.html) to create more comprehensive archives.
