### ISSUE TITLE
V2: Add support for preview.redd.it images

### ISSUE THREAD

**Issue by BlipRanger** [aliparlakci/bulk-downloader-for-reddit#253]
I've noticed a few image-based posts on reddit use the preview.redd.it link rather than something like i.reddit, etc. 
Would be nice to add this since I think the processing should be exactly the same as any other reddit image.

**Comment by Serene-Arc** [comment]
Are you sure that these don't download? If the link ends with a file extension then the regex will actually catch it still. If you have any example submission IDs I'll test and make sure.

**Comment by BlipRanger** [comment]
> Are you sure that these don't download? If the link ends with a file extension then the regex will actually catch it still. If you have any example submission IDs I'll test and make sure.

Here's the one I was testing on: 

https://www.reddit.com/r/discordian/comments/mki7dl/hi_there_my_name_is_ed_nusbaum_im_an_accountant/
and here is another:
https://www.reddit.com/r/catforscale/comments/mklnmo/catbot_this_sweet_potato_chonky_cat_for_scale_by/

Based on some reading/testing, I think we can just replace "preview" with "i" to get the full image.

**Comment by aliparlakci** [comment]
To clarify, the problem here is preview.redd.it links contain a smaller version of the image. However, post is actually a link to the image. Even reddit does not show the original image in the webpage. I think that is because post author copied the link from another post but the link was wrong (it was preview.redd.it link).

Long story short, BDfR works as expected here. Implementing such logic is against the nature of BDfR.

**Comment by BlipRanger** [comment]
> 
> 
> To clarify, the problem here is preview.redd.it links contain a smaller version of the image. However, post is actually a link to the smaller image. Even reddit does not show the original image in the webpage. I think that is because post author copied the link from another post but the link was wrong (it was preview.redd.it link).
> 
> Long story short, BDfR works as expected here. Implementing such logic is against the nature of BDfR.
> 
> I found the original post via reverse image search: https://www.reddit.com/r/interestingasfuck/comments/mib9zd/i_stacked_52_pictures_of_an_ants_head/

Perhaps I misunderstand, but shouldn't BDfR at least download the preview image then?

**Comment by aliparlakci** [comment]
I was able to download both of the posts successfully.

![image](https://user-images.githubusercontent.com/24864343/113597101-e55d3c00-9643-11eb-9c50-02777a58fb44.png)

**Comment by BlipRanger** [comment]
> 
> 
> I was able to download both of the posts successfully. Are you using the latest commit?
> 
> ![image](https://user-images.githubusercontent.com/24864343/113597101-e55d3c00-9643-11eb-9c50-02777a58fb44.png)

No, just pulled the latest and it's fixed. Must have been something since yesterday. Thanks!

**Comment by Serene-Arc** [comment]
Glad it works :)
