### ISSUE TITLE
Code doesn't work at all

### ISSUE THREAD

**Issue by kricketune** [aliparlakci/bulk-downloader-for-reddit#257]
After installing the requirements and running `python3 script.py`all I get are this message:
```
ERROR:root:KeyError
Traceback (most recent call last):
  File "/home/yaboi/Downloads/bulk-downloader-for-reddit/script.py", line 372, in <module>
    main()
  File "/home/yaboi/Downloads/bulk-downloader-for-reddit/script.py", line 273, in main
    sys.argv = sys.argv + GLOBAL.config["options"].split()
KeyError: 'options'

Traceback (most recent call last):
  File "/home/yaboi/Downloads/bulk-downloader-for-reddit/script.py", line 385, in <module>
    if not GLOBAL.arguments.quit:
AttributeError: 'NoneType' object has no attribute 'quit'
```

**Comment by azbe** [comment]
Solution: modify line 13 in src/utils.py to the following:
```
    config = {'imgur_client_id': None, 'imgur_client_secret': None, 'options': ''}
```

**Comment by aliparlakci** [comment]
I suggest you to switch to v2 unless you have a reason not to. Old version is going to to be replaced with v2 soon. You can refer to this comment if you have issue running the new version. https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/243#issuecomment-814348047

**Comment by kricketune** [comment]
When I clone the v2 repository and run python3 -m bulkredditdownloader`I just get `/usr/bin/python3: No module named bulkredditdownloader`

**Comment by aliparlakci** [comment]
@kricketune you must be in the root directory of the project to run the command

**Comment by aliparlakci** [comment]
Fixed
