### ISSUE TITLE
How to use v2?

### ISSUE THREAD

**Issue by PotatoLord73** [aliparlakci/bulk-downloader-for-reddit#265]
I attempted to use v2 the same way I use v1 but when I entered 'python script.py' into the command line I received an error message that said 'No such file or directory' What should I do to fix this?

**Comment by Serene-Arc** [comment]
There is no script file. If you look at the README for v2, there are several example commands and all of the arguments and options are explained. If you are in the root directory of the project, then you can use the following command to run  it:

```bash
python3 -m bdfr DESTINATION [args]
```

For example, to download 30 submissions from the subreddit r/python, it would be:

```bash
python3 -m bdfr DESTINATION --subreddit python --limit 30
```

Please refer to the README and documentation for further uses.

**Comment by PotatoLord73** [comment]
I went to the root directory, opened a PowerShell window and put the command you gave above and got an error that there is no module named bdfr in python.exe. What should I do? Apologies in advance I have very little knowledge of coding.

**Comment by Serene-Arc** [comment]
You may have to install the module. To do that, use the following command:

```bash
python3 -m pip install -e .
```

This will install an editable package, which means that you can pull changes. This isn't what I'd normally recommended but we don't have a package published on PyPi at the moment.
