### ISSUE TITLE
Redirect to /subreddits/search

### ISSUE THREAD

**Issue by Dimebag-Darrell** [aliparlakci/bulk-downloader-for-reddit#273]
What does it mean if I get the message Redirect to /subreddits/search
How can I solve?
Thank you

**Comment by aliparlakci** [comment]
Can you provide more information such as logs, the command you used to start the program, the post you encountered this issue?

**Comment by Serene-Arc** [comment]
Hi. I can respond. This is for v1 of the BDFR, which has been superseded by v2 and is no longer supported. Please move to v2 as we cannot provide help with v1 any longer, this issue won't happen in the new versions. Thanks :)
