### ISSUE TITLE
[FEATURE] Add option to download the comment context when downloading all comments of an user.

### ISSUE THREAD

**Issue by Fakeaccount12312** [aliparlakci/bulk-downloader-for-reddit#322]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](README.md#configuration)
  
## Description
You are able to download all comments of an user with --all-comments, but this does only include what this user wrote. Comments are often replies to another user, so it would be nice if there was an option  to either download the thread the comment belongs to or all comments of this post, something like --all-comments-with-context.

**Comment by Serene-Arc** [comment]
Just to clarify, do you want to download the entire submission that the user has commented on? That will grab every content including the one from the user in question.

**Comment by Serene-Arc** [comment]
@Fakeaccount12312 I'd like to do this before the next release if possible, switching to downloading every submission on which the user has commented would be my go-to for this and would give the most context.

**Comment by Fakeaccount12312** [comment]
Grabbing the whole post would be a good idea for some cases and should definitely be an option, but it may be a hassle if you want a lot of comments and your storage is limited. Thinking about this, two options might be a good idea, one to download the whole post including all other comments (like --all-comments-with posts) and one just for the specific thread (like --all-comments-with-parents).
