### ISSUE TITLE
Summary information about how many files were downloaded, skipped, etc. Last version had it [FEATURE]

### ISSUE THREAD

**Issue by ymgenesis** [aliparlakci/bulk-downloader-for-reddit#339]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](README.md#configuration)
  
## Description
Would like to submit a feature request to show summary info at the end of each command iteration which outlines how many items were downloaded, skipped (whether due to --skip or hash no dupes), total processed (before skipping or downloading). Helps to know exactly how much had been downloaded/skipped/assessed for download. 

For example:
```
[2000-01-01 12:00:,000 - root - INFO] - Program complete
[2000-01-01 12:00:,000 - bdfr.downloader/root - INFO] - Downloaded: n, Skipped: n, Total processed: n
```
The 1.x of bulk-downloader-for-reddit showed this info as part of the command output stream. 

I also wonder if there's a way to put whitespace around the lines in the output stream which signify a download/file write when using --verbose. Would help make it easier to visually pinpoint which files were downloaded when watching the command's output when using --verbose. Is there something I could alter if it's a simple addition? 

Thanks for the help!

**Comment by Serene-Arc** [comment]
@ymgenesis I can answer this in parts. For the whitespace around the info log entries, no we can't do that. I don't know of a mechanism that allows that and it's kind of besides the point. If you want to only see the info level entries, don't include the `--verbose` flag. Then you'll be able to see it more clearly, that's the mechanism for resolving that issue.

For the summary statistics, that isn't really part of the idea for the BDFR in it's current form. It is meant as a tool where it can be run regularly as a cron job, for instance, without human interaction. In that vein, it is imo a better and more flexible option to generate these end-of-run statistics from the logfiles themselves. There is far more possible statistics that can be generated this way and it allows for a much more fine-tuned look at the run according to your needs. If you don't know how to do that, I can add a Bash script to the `scripts/` directory as an example.

**Comment by Serene-Arc** [comment]
@ymgenesis There is now an example script in the `scripts/` folder called `print_summary.sh` that will do what you said. It's a Bash script and it's a pretty good example of how simple (relatively speaking) it is to extract whatever statistic you want from it.

**Comment by ymgenesis** [comment]
Thanks for the example script. I will do some tests!
