### ISSUE TITLE
[BUG] Filenames differ between macOS and Ubuntu

### ISSUE THREAD

**Issue by ymgenesis** [aliparlakci/bulk-downloader-for-reddit#348]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](README.md#configuration)
  
## Description
Filenames present themselves differently between macOS 10.14.6 and Ubuntu 20.04. Data was downloaded and stored on an external, formatted as exFAT, and connected to Ubuntu machine. Connecting to the drive over samba via macOS with full permissions, filenames show differently than when viewing on Ubuntu. Happens in macOS Finder vs Gnome Nautilus, as well as macOS Terminal (when browsing the samba share) vs. Gnome Terminal. SSH from macOS to Ubuntu machine the filenames are all proper. Version 1 didn't have this issue, so I'm not too sure if samba is the problem. Was using the same exFAT samba-connected drive with v1. 

You can compare the timestamps and file sizes in the Ubuntu screenshots to deduce what the filenames should be in the macOS screenshots. Same drive & directory/path. Only difference is that macOS is connecting to the drive over SMB on the Ubuntu machine. Some filenames are retained in the macOS side, but those files aren't special in name, size, and timestamp as far as I can tell. 

Maybe some way the program writes the files out that Unix has an issue with displaying? Some sort of resource fork issue? Just guessing. I have no idea why this would happen.

using an example from the NSFW sub gonemild, which is where I first encountered the bug/difference.

## Command
```
python3.9 -m bdfr download [DIRECTORY] --verbose --search-existing --no-dupes --subreddit gonemild --sort new --limit 10 --time week
```

Logs don't throw any errors, everything processes and downloads successfully. 

## Environment (please complete the following information):
 - OS: macOS 10.14.6 and Ubuntu 20.04
 - Python version: 3.9.4
 - Development branch pulled May 3

## Screenshot Examples (SFW)

**Ubuntu Nautilus showing all proper filenames:**

![UbuntuNautilus](https://user-images.githubusercontent.com/25252829/117236438-ad8a1580-adf6-11eb-9efa-b9a3c37aa176.png)
**macOS Finder showing some sort of IDs (not related to bdfr's IDs) instead of filenames (over samba):**

![MacFinder](https://user-images.githubusercontent.com/25252829/117236443-b37ff680-adf6-11eb-97d5-f55fc5d98a8a.png)
**Gnome Terminal showing all proper filenames/timestamps/sizes:**

![UbuntuTerminal](https://user-images.githubusercontent.com/25252829/117236450-b7137d80-adf6-11eb-8a9d-cb2aeb50d218.png)
**macOS Terminal showing IDs instead of filenames, with timestamps/sizes (browsing mounted samba share. SSH from macOS to Ubuntu filenames are all proper.):**

![MacTerminal](https://user-images.githubusercontent.com/25252829/117236457-b975d780-adf6-11eb-9583-728bc5c6510d.png)

**Comment by Serene-Arc** [comment]
This is a SAMBA issue. You'll note that there is a pattern: if the filename on Ubuntu contains a question mark (?), it will switch to the alternative ID. This is a restriction that SAMBA implements due to similar restrictions existing on Windows. In the Windows file system, `?` is an invalid character and can't be included in a filename. 

To fix this, I would suggest using NFS or an alternative file-sharing service.

**Comment by aliparlakci** [comment]
The reason this is not the case with v1 is that, back then, the filenames were sanitized according to Windows restrictions, independent from the platform. In v2, this process is platform-aware.

A simple solution to this to run a simple script after bdfr run that will remove the problematic characters from the filenames.

**Comment by ymgenesis** [comment]
Was just writing one, thanks very much.

I run it on Linux, so it makes sense to be sanitized as such on that platform. Mac uses 3.0 version of samba. 3.5 has an ability to map special characters to others, which would be favorable instead of altering content. Nevertheless, thanks again!

**Comment by Serene-Arc** [comment]
@ymgenesis My philosophy has been that, as a downloader, the BDFR should preserve as much information as possible to be true to the source. It won't change the name of the file unless absolutely necessary, since Linux has the best filename policy out there. On Windows it will clean the name of the files to make them compatible but you loose a lot of possible data.

I use NFS to view fileshares between compatible systems, and only resort to SAMBA when necessary. If you have the ability to use that, it's the no-compromise method really

**Comment by ymgenesis** [comment]
Makes sense to me. I will look into working with NFS on macOS when I have the time. 

Otherwise, I just added some code to my BASH script that removes all characters except letters, numbers, dashes, underscores, and periods. I feel better having it sanitized so it'll be ready for anything, anyhow.
