### ISSUE TITLE
[FEATURE] Consider binding OAuth socket to hostname rather than localhost

### ISSUE THREAD

**Issue by BlipRanger** [aliparlakci/bulk-downloader-for-reddit#366]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
When running bdfr in a containerized environment, binding the socket used to receive the OAuth token info to 'localhost' causes complications and makes it impossible to expose the port externally. I would like to propose binding to the hostname or at least providing the ability to configure the hostname via an env var. 
I have tested using ```host = socket.gethostname()``` as the source of the host to bind to and have confirmed it works from within containers and on host machines.  I'd be more than happy to write, test, and PR this change if you think it would be helpful. Thanks!

**Comment by Serene-Arc** [comment]
Seems a pretty simple change, you're more than welcome to implement this :)

**Comment by aliparlakci** [comment]
This breaks the OAuth 2.0 process entirely. Reddit only redirects to the link that is given in the project settings of BDFR in the reddit console. It is http://localhost:7634 and is neither changeable nor dynamic. We did not choose to use it that way, by the way. This is the standart OAuth 2.0 authentication flow.

On the other hand, your proposal is not a good way of handling the problem either. Docker solves this issue with port mapping. Have a look at the documentation of Docker here: [Container Networking](https://docs.docker.com/config/containers/container-networking/)

**Comment by BlipRanger** [comment]
Sorry, I think there must be a misunderstanding. I do a lot of work with docker containers and understand how port mapping and networking in docker works. This is after mapping 7634 to 7634 externally. The port will not even show as open, despite being open in the container and mapped on the container if the interface that you bind to is localhost. 

How do you recommend authing bdfr on a headless server where someone might be using the script in an automated fashion? So far I just have replaced "localhost" in the redirect url with the address of the server and that works just fine (or wget the redirect url on the server itself). This does not work within a container if the socket is bound to localhost, however it does work in the container if the socket is bound to the hostname or to 0.0.0.0. I really don't think this breaks OAuth 2.0 at all since it is still receiving all traffic directed at localhost.  

Would you consider at least allowing this to be defined as an environment var with the default set to "localhost"?

**Comment by aliparlakci** [comment]
Now I understand the problem you are having. I thought you were trying to change the location reddit redirects the user to.

In the earlier versions, I did bind the socket to "0.0.0.0" instead of "localhost", as you said: [link](https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/119/files#diff-bde39d5878e4fc7379d8f13e9f46a686312224a4fe30b3bb7cdacb2e57ff5eaf). However it seems Serene didn't implemented it in v2.

Yes, we will be very pleased to have your contribution :)

**Comment by BlipRanger** [comment]
Sure, I'll get the PR in soon. Thanks!
