### ISSUE TITLE
[BUG] I must just be stupid

### ISSUE THREAD

**Issue by AplhaSlayer1964** [aliparlakci/bulk-downloader-for-reddit#390]
- [X] I am reporting a bug.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
'bdfr' is not recognized as an internal or external command,
operable program or batch file.
Used pip install --upgrade bdfr everything says it's installed and up to date but when trying to run nothing happens.
I am able to use other programs such as youtube-dl and gallery-dl just fine from the comand prompt. 
Also to note this is a freshly installed winodws 10 pro and python3 with no settings changed from default.
I have tried other combinations of commands and the example commands all give the same errors listed bellow.

## Command
```
bdfr download directory "Z:\TEST" --submitted --user (any user)
^ outputs not a reconized command
python3 -m bdfr download directory "Z:\TEST" --submitted --user (any user)
^ just outputs nothing
```

## Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.9.5

## Logs
```
No longs python doesn't seem to want to even reconize the script.
```

**Comment by Serene-Arc** [comment]
Please read the examples in the README in the repository before opening an issue. You can call the BDFR with `python3 -m bdfr download Z:\Test --submitted --user <USER>`. "directory" is not a valid argument as included in your commands.

**Comment by AplhaSlayer1964** [comment]
Just tried 
python3 -m bdfr download Z:\Test --submitted --user (some username)
bdfr download Z:\Test --submitted --user (some username)
and get the same result either nothing happens or bdfr is not a valid command.

**Comment by Serene-Arc** [comment]
You say it's a fresh install. Have you installed Python 3.9 onto this system?

**Comment by AplhaSlayer1964** [comment]
Yes I have. And other pip installed scripts work fine thats why i'm really confused.

**Comment by aliparlakci** [comment]
When you have more than one installation of Python on your system, it is not clear what Python version `pip` installs the packages for.

My suggestion is, run the below commands and select the Python keyword which outputs at least 3.9:
```
python --version
python3 --version
python3.9 --version
py -3.9 --version
```

Then, install bdfr through Python. Replace the `python` with the correct keyword you found in the previous step.
```
python -m pip install bdfr --upgrade
```

Try running bdfr through Python. Again, replace the `python` with the correct keyword you found in the previous step.
```
python -m bdfr download ./out --user aliparlakci --submitted -L 3
```

**Comment by AplhaSlayer1964** [comment]
Using just "python" seems to have solved it. Really weird because I swear I tried just python before along with python3 and nothing. Also when I said outputs nothing it really did just output nothing like this:

C:\Users\User>python3 -m bdfr download ./out --user aliparlakci --submitted -L 3

C:\Users\User>_
