### ISSUE TITLE
PRAW Authentication Error when account has 2FA.

### ISSUE THREAD

**Issue by chriscn** [aliparlakci/bulk-downloader-for-reddit#4]
I use 2FA on my reddit account and so should you 😄 . 
However this script will not work with 2FA because PRAW requires the 6 digit code that simply isn't provided as referenced [here](https://www.reddit.com/r/redditdev/comments/74cu2i/praw_two_factor_authentication_and_script_apps/). The way for getting around this currently is that I made a second reddit account without 2FA and am using that instead. 

The issue with this script is that you would need to program it so that it asks for the 2FA on run every time because as is the nature of 2FA it changes.

**Comment by aliparlakci** [comment]
I will fix it. Although it is really easy to fix, I totally missed that.

**Comment by aliparlakci** [comment]
The feature has come. Either get [v.1.1.0-alpha.1](https://github.com/aliparlakci/bulk-downloader-for-reddit/releases/tag/v1.1.0-alpha.1) or pull master branch.

There still might be bugs. Post the issues you have here, please.
