### ISSUE TITLE
[FEATURE] Using a text file with --user

### ISSUE THREAD

**Issue by AplhaSlayer1964** [aliparlakci/bulk-downloader-for-reddit#410]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Allow multiple users to be searched by reading each line of a given text file.

**Comment by aliparlakci** [comment]
You can achieve this with a dead simple script file. If you are on Windows, create a `download_users.bat` containing the following

```bat
python -m bdfr dowload ./out --user USER1 --submitted
python -m bdfr dowload ./out --user USER2 --submitted
python -m bdfr dowload ./out --user USER3 --submitted
```

Replace the USERX with the correct redditor names and extend the list. Let us know if that does not work for you.

**Comment by AplhaSlayer1964** [comment]
ya but my list is so long I had to make a script to make that script lol and to bust it up to run it in parallel. It's no big deal if this isn't added just thought it would be nice.

**Comment by Serene-Arc** [comment]
You can use xargs to do something like this pretty easily. You can use a list of names in a text file easily with that.

**Comment by aliparlakci** [comment]
> ya but my list is so long I had to make a script to make that script lol and to bust it up to run it in parallel.

Your use case is not that rare, imo. I suggest you to open a Discussion and we can provide the necessary script file to you there. So that others with the same issue can also benefit.

The reason we are not implementing such features is that we are afraid of bloating the program to a point where it is both non-usable and non-maintainable.
