### ISSUE TITLE
[FEATURE] --search-exisiting only on designated --folder-scheme folder not directory 

### ISSUE THREAD

**Issue by AplhaSlayer1964** [aliparlakci/bulk-downloader-for-reddit#411]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
It would be nice to have a flag to do --search-existing but only on the subfolder created by --folder-scheme. Manly would be used when saving multiple reddit profiles instead of multiple subreddits.

**Comment by Serene-Arc** [comment]
I'm not sure how this would be possible. The point of the `--folder-scheme` is to make a dynamically named folder, if required, to sort and/or categorise the files downloaded. There is not necessarily a subfolder at all, so unless I'm misunderstanding your request, I don't think it can be done.

**Comment by aliparlakci** [comment]
It sounds like this can be achieved with shell scripts. You can open a Discussion if you are require help setting up the scripts.

Due to the request being too specific such that it adds unnecessary complexity to the project for both users and maintainers, I am closing it. Should the converse is proven, we can reopen it.

**Comment by Serene-Arc** [comment]
IMO the solution is a third-party tool like `rdfind`. That's pretty good

**Comment by fbck** [comment]
the point would be to prevent redownloading of files from happening and saving time by not even fetching posts that are going to be duplicate, instead of just downloading everything and removing duplicates later

**Comment by Serene-Arc** [comment]
I wouldn't expect the Venn diagram of posts that have identical files to other posts and posts that have the same file but a different ID to be that large. If it's such an issue, then the solution is merely to make the subfolder the root for the program and use the `--search-existing` flag on that then.

There is no way to know beforehand what folders will be created by the folder scheme except in trivial circumstances and, as I have said in other issue posts, `--search-existing` is a mediocre solution to the problem. Tools like I suggested, `rdfind` among them, use more sophisticated heuristics to determine if files are identical, drastically cutting down the time. None of that is implemented in the BDFR, nor could it be in this use case. 

Considering the small number of files that would be caught by this, I would say that if you're so worried about bandwidth or data, you shouldn't be downloading things at all. Unless you're downloading large videos that are uploaded multiple times to multiple subreddits but not crossposted, then the time to download would be minimal compared to even the processing time that `--search-existing` adds i.e. it would be faster to simply disable the option, download things multiple times, and then run rdfind every dozen runs or so.
