### ISSUE TITLE
[FEATURE] archive file to store hashes to save time re computing them again

### ISSUE THREAD

**Issue by AplhaSlayer1964** [aliparlakci/bulk-downloader-for-reddit#412]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Some type of archive file to be created that stores the post id's or file hashes to skip already downloaded posts quicker.

**Comment by aliparlakci** [comment]
It sounds like what you need is [Extract all Successfully Downloaded IDs](https://github.com/aliparlakci/bulk-downloader-for-reddit/tree/master/scripts#extract-all-successfully-downloaded-ids)

**Comment by AplhaSlayer1964** [comment]
That does seem like what I'm looking for but im on a windows machine. I'll see if runing WSL will let me run the bash script.

**Comment by Serene-Arc** [comment]
An equivalent should be quite easy to write as a powershell (.ps1) script.
