### ISSUE TITLE
[BUG] Hash calculation takes up all the system memory for directories with large files.

### ISSUE THREAD

**Issue by ymgenesis** [aliparlakci/bulk-downloader-for-reddit#416]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
The ability to limit downloading submissions at and over a certain file size, or another solution that would remedy the hash calculator taking up all memory and causing a system crash. Wasn't sure about labeling this bug or feature.

## Context
Because the youtube-dl fallback has been added, some of the videos bdfr downloads when I point it at a subreddit can be large in size (not ususally the case for say imgur/gfycat/redgifs). As such, when bdfr is run again (using `--search-existing ` and `--no-dupes` as usual), and is pointed at the same subreddit folder to get updates, it begins calculating hashes for these large files. In my example, there's only 15 files, all adding up to a 10gb directory.

The Ubuntu 20.04 laptop I use has 8gbs of RAM. When it begins calculating these hashes, it quickly takes up all the RAM, Ubuntu panics, all peripheral input is lost, and my laptop must be forcefully restarted by holding the power button. 

I analyzed my syslog at the time of the crash and it pointed to python3.9 with the correct PID as the culprit, after which no logs are written, and I forcefully restart. It shows out of memory (oom) trying to remedy the situation:

```
May 21 11:44:18 hostname kernel: [ 2671.186170] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=python3.9,pid=7385,uid=1000
May 21 11:44:18 hostname kernel: [ 2671.186181] Out of memory: Killed process 7385 (python3.9) total-vm:1629364kB, anon-rss:784952kB, file-rss:0kB, shmem-rss:4kB, UID:1000 pgtables:2040kB oom_score_adj:0
May 21 11:44:18 hostname kernel: [ 2671.252607] oom_reaper: reaped process 7385 (python3.9), now anon-rss:0kB, file-rss:0kB, shmem-rss:4kB
```

Other than letting the user limit filesize, could there be a tweak to the hash calculation process to stop calculation if it reaches something like 80% (or some other percentage) of system memory? Maybe an option to disable the youtube fallback downloader?

I ran my script again and monitored the memory as it tried to calculate hashes for the specific folder. It went from ~20% to 90% and above as it calculated those hashes, as I suspected. [Here's a screenshot](https://i.imgur.com/NJNZhOK.png) of the memory reaching close to max capacity, and my attempt to ^c bdfr a couple times while it calculated the hashes (_calc_hash). It locked up shortly after. The keyboard interrupts didn't stop the memory usage from rising as fast as I thought it would 😛

**Comment by aliparlakci** [comment]
This is a rather interesting issue. We didn't thought about using up all the system memory. We will look into ways to optimize hashing. I am not that eager to implement a limit size parameter unless we have no other choice.

In the mean time, I can suggest you a solution which might ease the load on the system. Currently, we are hashing up to 15 files in parallel. You can lower this number such that you can hash the largest file in your directory with 8GB of memory.

```python
# ./bdfr/downloader.py
def scan_existing_files(directory: Path) -> dict[str, Path]:
      files = []
      for (dirpath, dirnames, filenames) in os.walk(directory):
          files.extend([Path(dirpath, file) for file in filenames])
      logger.info(f'Calculating hashes for {len(files)} files')

      pool = Pool(15) # Try making this number 1
      results = pool.map(_calc_hash, files)
      pool.close()

      hash_list = {res[1]: res[0] for res in results}
      return hash_list
```

**Comment by ymgenesis** [comment]
Ah I see. I didn't realize it calculates more than 1 file at once. Interesting solution, I'll put that in for now. Thank you!

**Comment by aliparlakci** [comment]
Can you verify that the commit I pushed solves your issue?

**Comment by ymgenesis** [comment]
No problem:) 
I removed the files. I'll run bdfr again to download them, then re-run without your commit to make sure the issue is there, then I'll implement your commit and let you know if it fixed the issue.

**Comment by Serene-Arc** [comment]
@ymgenesis This is definitely something I didn't anticipate when I wrote the code and I guess that this use case is rare since no one has reported it before. I would hazard a guess that the BDFR is predominantly used to download smaller files. 

Incidentally, the ability to disable downloader modules is coming, there's an open enhancement request with it.

**Comment by ymgenesis** [comment]
Considering the fallback youtubedl pretty much acts as a catch-all, I'm sure it's expected that downloads will vary in size and 'use cases'. Starting the commit tests now.

**Comment by ymgenesis** [comment]
That helped considerably. Does the chunking slow down the calculations any?

**Comment by Serene-Arc** [comment]
It's unlikely to be significant.

**Comment by ymgenesis** [comment]
Thanks
