### ISSUE TITLE
[FEATURE] Performing downloading and archiving at once with a single command

### ISSUE THREAD

**Issue by 1105420698** [aliparlakci/bulk-downloader-for-reddit#420]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
The ability to download Reddit media while archiving its corresponding comments and other context data, this avoids problems that could occur when a post is made or deleted between the download and archive stage, causing some downloads that does not have archive data, or vice versa.

**Comment by aliparlakci** [comment]
We were planning to implement it. Hopefully, it will in the next release.

**Comment by Serene-Arc** [comment]
I've got 75% of a PR written that does exactly this
