### ISSUE TITLE
Login without web browser on headless Linux

### ISSUE THREAD

**Issue by ogtimothymiller** [aliparlakci/bulk-downloader-for-reddit#43]
I am trying to use your library on a headless linux server on Docker. Because the Reddit API authorization requires logging into the web browser, it cannot be accomplished.

Can you add the option to enter the Reddit API details in a txt file?

**Comment by aliparlakci** [comment]
There is already an option for that. Run the script from a machine that is not headless and login to reddit. 
Your secret key will be store in _config.json_ file in your _Home_ directory inside "_Bulk Downloader for Reddit_" folder. 
Replace the config.json file on the headless machine with the one that has your login information.

If you can't find the file on Linux machine, please return and I will try to help further.

**Comment by aliparlakci** [comment]
I want to add I am concerned that you will be able to use it as "library" or in my understanding _module_. Because it is not designed to be if that is what you mean, then ok.

**Comment by aliparlakci** [comment]
Thanks, appreciate it!
(Yes, I reopened it just to say thanks :D)

**Comment by aliparlakci** [comment]
Oh, so you can still post comments even if the issue is closed?
Interesting...

**Comment by ogtimothymiller** [comment]
You are reopening the issue every time you comment, my dude.

**Comment by aliparlakci** [comment]
Actually I am not.

See?
