### ISSUE TITLE
[FEATURE]vid.me download support

### ISSUE THREAD

**Issue by nascentt** [aliparlakci/bulk-downloader-for-reddit#436]
- [X ] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [ ] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
vid.me is a popular video host used by a lot of subreddit's I'm on, but bdfr just fails them all: "No downloader module exists for url https://vid.me/"

would be great to get support

**Comment by Serene-Arc** [comment]
@nascentt Can you please explain why you want this? The website in question seems to have shut down over four years ago and no longer exists. If this is incorrect, please provide working links so I can investigate.

**Comment by nascentt** [comment]
yup, you're completely right. I didn't actually check them, just saw thousands of the links the downloader skipped over because it wasn't supported. pity but there's nothing much you can do if the site's dead.

appreciate the support, this can be closed

**Comment by Serene-Arc** [comment]
@nascentt if it helps and there is content that you absolutely want, it appears to have been bought by Giphy, so you may be able to find it there.
