### ISSUE TITLE
[FEATURE] Date range limit

### ISSUE THREAD

**Issue by besleFj** [aliparlakci/bulk-downloader-for-reddit#439]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
The ability to set a date range (To/From, AND/OR) that allows to grab posts within this date range. Would be perfect if either of the parameters could be omitted for a full search to or from the given date.

**Comment by Serene-Arc** [comment]
If you can't do it from Reddit, we can't do it with their API. This isn't possible for us to accomplish. The current advanced search information can be found [here](https://www.reddit.com/wiki/search) but it unfortunately doesn't provide any way to filter based on time and it appears that there is now way to do through Reddit at all.

The easiest way to do this at the moment is with the general time range already supported, include the timestamp in the filename, and then delete the ones outside the range.

Note also that the Reddit ranges are approximate only. Restricting to the last day of posts does not always give posts from the last 24 hours.
