### ISSUE TITLE
Proxy requests

### ISSUE THREAD

**Issue by ogtimothymiller** [aliparlakci/bulk-downloader-for-reddit#44]
It would be nice if there were an option to proxy your connections to download content through a proxy to avoid rate limiting.

**Comment by aliparlakci** [comment]
So, you want to specify a proxy server you have chosen when requesting files from servers. I can implement an option for it.

But do you want to jump between proxies on a list?

I should warn you that there is still 1250 request limit for each imgur api app. I am afraid you couldn't get around that.

**Comment by ogtimothymiller** [comment]
Yes, that is correct. I think adding the option in a command line argument to specify a proxy address, username, and password is more than enough. People might value the option to handle the sourcing and handling of proxy addresses from public and private sources.

Imgur's API page says 12,500 requests per day, 1,250 uploads per day. But if you hit the rate limit five times in a month, they ban you for that month.

**Comment by aliparlakci** [comment]
I might have forgotten one zero :D
  
Using a list of proxies looks more interesting though. I will try to implement that.
  
Thank you!

**Comment by aliparlakci** [comment]
@ogtimothymiller Can you checkout [ProxyFeature](https://github.com/aliparlakci/bulk-downloader-for-reddit/tree/ProxyFeature) if it is stable and does the job? I cannot since I don't use any proxy.

**Comment by ogtimothymiller** [comment]
I'll test out the new features with a private dataset this afternoon.

**Comment by aliparlakci** [comment]
I recently figured out that imgur api doesn't support using proxies. It means that even if you use a proxy server to download the file, imgur api wouldn't as it gets the posts from the server. But you can still give it a shot for an unexpected result.
