### ISSUE TITLE
gfycat error

### ISSUE THREAD

**Issue by curiousgm** [aliparlakci/bulk-downloader-for-reddit#45]
Whenever I try to download a gif with a gfycat link, I get this error. I have used this downloader before and didn't have an issue. I tried a fresh install and it still doesn't work. Is there something else I should try?

Here is an example post which produces an error:
{
    "HEADER": "C:\\Bulkdownloader\\bulk-downloader-for-reddit.exe",
    "1": [
        "NotADownloadableLinkError: Could not read the page source",
        {
            "postId": "9at3ik",
            "postTitle": "A master hunter in action",
            "postSubmitter": "RespectMyAuthoriteh",
            "postType": "gfycat",
            "postURL": "https://gfycat.com/BoldSlightGibbon",
            "postSubreddit": "funny"
        }
    ]
}

here's the message in the console:

(1/1) – r/funny – GFYCAT
NotADownloadableLinkError: Could not read the page source
 Nothing downloaded :(

Thanks!

**Comment by aliparlakci** [comment]
I see. Can you try older versions until I investigate the issue and fix it?

**Comment by aliparlakci** [comment]
It seems that Gfycat changed their website. I have to change the algorithm I use to get gfycat links.

**Comment by aliparlakci** [comment]
Fixed it at 1.6.4 version.

**Comment by curiousgm** [comment]
Awesome, thank you!
