### ISSUE TITLE
[FEATURE] Add progress bar for downloads

### ISSUE THREAD

**Issue by ghbook** [aliparlakci/bulk-downloader-for-reddit#469]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Thanks for this awesome program. While downloading large files via `download` there is no way to tell whether the terminal has frozen or doing network requests. It will very be helpful if there is some info while processing request.

**Comment by Serene-Arc** [comment]
This isn't going to be done with this part of the BDFR sorry. There are plans to create a user interface with more feedback but that isn't the purpose of this tool. The core BDFR is meant to function as a script and a cron job, both of which can't do progress bars. The BDFR is not mean to be looked at constantly, but run in the background if necessary.

I would suggest taking a look at your network usage if you want to know if it's stuck. There are a great many tools that will show you what processes are using the network interface. There is a current bug where the BDFR does get stuck on PornHub submissions but hopefully that will be fixed soon.

**Comment by stared** [comment]
@ghbook If you are fine with running a local version, here you are: #697 .
