### ISSUE TITLE
Feature Request: add auto-wait when API gets a temporary lock

### ISSUE THREAD

**Issue by bartrail** [aliparlakci/bulk-downloader-for-reddit#49]
When downloading quite a lot of images after some time there is a message saying that it will be resetted (right now after 20 minutes):
`==> Client: 11573 - User: 0 - Reset after 20 Minutes 26 Seconds`
After every following request one can see how the countdown decreases. It would be nice if the script could auto-detect this waiting time and sleep until the message disappears. After that it can continue the downloading (until the next waiting time appears and so on..)

**Comment by bartrail** [comment]
you're right, the commercial account would solve this issue quite elegantly. In my eyes, having a programm "sleep" for 20+ minutes wouldn't be bad thing at all - that's why I proposed this feature.  But having failed downloads in a log file and retry those ones manually later solves this issue also pretty good. Thanks for explaining.

**Comment by aliparlakci** [comment]
I see your point at "sleeping for 20+". Please pardon me if I sounded mean as I used "useless" earlier, I should have been more clear on the downside of it. Let me explain it further:

Think of a case where you are downloading from a **multireddit**. There are subreddits just contain imgur links, gfycat links, direct image links or maybe albums. Your first 1000 links are pure imgur links and the following 2000 links are gfycat links or maybe self posts. Depending on your connection speed, you are bound to wait 20+ minutes. But you would want to use that 20 min to download remaining 2000 posts.

For example, I leave my computer on at nights to download from reddit but I can't sleep on the fan noise of it. The sooner it shuts itself, the sooner I fall asleep.

(Please excuse my english. It might be a bit off. I am on the edge of forgetting it all as I didn't use it on daily basis.)
