### ISSUE TITLE
Use xdg specification

### ISSUE THREAD

**Issue by BurhanDanger** [aliparlakci/bulk-downloader-for-reddit#50]
Really great software. Thanks for this. There's one thing bugging me. `Bulk Downloader for Reddit` directory in my home folder looks cluttered to me. Can you move it to `~/.config` so that it becomes `$HOME/.config/Bulk Downloader for Reddit/config.json`

Edit: Also I think it's good idea to drop space.

**Comment by aliparlakci** [comment]
Thanks for the feedback!

Unfortunately, I don't really have the time to work on it. I have currently
been studying for an important test I will take this summer to attend
university, YKS.

But I would be greatful if you can implement it. Then I can merge it to the
project and give you credit.

**Comment by BurhanDanger** [comment]
Sorry I don't know python very well. I'll check to see what I can do.
