### ISSUE TITLE
[BUG] --no-dupes doesn't appear to be working properly

### ISSUE THREAD

**Issue by Qwerty-Space** [aliparlakci/bulk-downloader-for-reddit#505]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
Even with --no-dupes enabled, many duplicates still get through.  rmlint is able to detect them.
I see `Resource hash ... downloaded elsewhere` but it doesn't catch all of them.

## Command
```
python -m bdfr download . --authenticate --subreddit friends --no-dupes --folder-scheme {REDDITOR}
```

## Environment (please complete the following information):
 - OS: Arch Linux
 - Python version: 3.9.6

**Comment by Qwerty-Space** [comment]
I'll provide the reddit submissions in private, if you like.

**Comment by Serene-Arc** [comment]
It's fine, this is the expected behaviour of the program. The `--no-dupes` function only removes duplicates for which it has the hashes. It calculates these during the download or for existing files with the `--search-existing` option. So, if you do not use that option, the `--no-dupes` option will *only remove duplicates it finds on that single run of the BDFR*.

If you want to find duplicates that are already on file, use `--search-existing`. However, this is honestly a bad solution and is not recommended since it takes ages to scan even a relatively small amount of files. My recommendation is to use `--no-dupes` and then use another tool like rdfind to find the rest of the actual duplicates.

**Comment by Qwerty-Space** [comment]
Aha!  Thank you.  I'll continue using rmlint to remove duplicates then

**Comment by Qwerty-Space** [comment]
Would it be possible to save the hashes, and re-use them on a subsequent run?

**Comment by Serene-Arc** [comment]
No, that is not possible. The BDFR is a stateless downloader and doesn't record any information between downloads outside of the logs. It is a common use case to extract IDs of all submissions downloaded and then skip these on the next run. That prevents literally the same submission from being downloaded again, and then identical files can be dealt with with other tools.

**Comment by Qwerty-Space** [comment]
That's disappointing.  It would be nice to be able to have a flag to save the hashes to a file if need be!

**Comment by Serene-Arc** [comment]
There shouldn't be that much redownloaded if you remove completed IDs. To redownload it means that it needs to be the exact same submission uploaded somewhere else that isn't a crosspost. That shouldn't be many things. 

The issue with saving hashes is that it doesn't guarantee that it's an accurate representation of the library. Things like tagging, metadata changes, or other optimisations to files can result in a completely different hash and there's no way to check for that.

**Comment by Qwerty-Space** [comment]
> There shouldn't be that much redownloaded if you remove completed IDs. To redownload it means that it needs to be the exact same submission uploaded somewhere else that isn't a crosspost. That shouldn't be many things.
> 
> The issue with saving hashes is that it doesn't guarantee that it's an accurate representation of the library. Things like tagging, metadata changes, or other optimisations to files can result in a completely different hash and there's no way to check for that.

It is a hell of a lot for some users.  They post the same thing in a dozen or more subs.
