### ISSUE TITLE
[FEATURE] Using the --saved option, anything applied in the --search option will be applied.

### ISSUE THREAD

**Issue by user4302** [aliparlakci/bulk-downloader-for-reddit#506]
- [✔] I am requesting a feature.
- [✔] I am running the latest version of BDfR
- [✔] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
This feature will work on posts saved in the user account.
The feature would be the ability to use the search [--search] function on saved posts.

**Comment by Serene-Arc** [comment]
This is not possible through the Reddit API afaik. There's no way to implement this without downloading all of the posts anyway and then sorting through them.

**Comment by user4302** [comment]
oh ok, thats fine then, thank you.
