### ISSUE TITLE
[FEATURE] Vidble downloader

### ISSUE THREAD

**Issue by Soulsuck24** [aliparlakci/bulk-downloader-for-reddit#515]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Currently when the downloader reaches a vidble link it falls back to youtube-dl but is not supported there so receive errors such as: `bdfr.downloader - DEBUG] - Attempting to download submission oss5g5`
`bdfr.site_downloaders.fallback_downloaders.youtubedl_fallback - ERROR] - ERROR: Unsupported URL: http://vidble.com/show/RDFbznUvcN`
`bdfr.downloader - ERROR] - Could not download submission oss5g5: No downloader module exists for url https://vidble.com/show/RDFbznUvcN`
Not sure if the imgur downloader could be used as a starting place but it would be great to get this site with a downloader as it seems to be a reasonably popular alternative to imgur.

One oddity that may cause issues for creating a downloader I've noticed though is most images (single or gallery, but not all) have "_med" appended to the filename. removing it does give the full res image but it seems to only be images that it happens with. Not sure how difficult it would be to remove that on the fly, if it's there, to get the higher quality image. I've added some reddit links and a direct link for examples.

***NSFW links***
https://reddit.com/oss5g5 (single image)
https://reddit.com/i7z972 (gif)
https://reddit.com/69xvit (gallery)
https://reddit.com/lggg8j (mp4)
https://reddit.com/8yuhm0 (single full image)
https://www.vidble.com/show/P0R17ma4EY (single image)

**Comment by Serene-Arc** [comment]
Thanks I'll look into it
