### ISSUE TITLE
"HTTPError: HTTP Error 403: Forbidden for posts" for video files hosted on Reddit

### ISSUE THREAD

**Issue by memyselfandhai** [aliparlakci/bulk-downloader-for-reddit#54]
Just ran through 100 saved posts & all worked just as expected except video files hosted on Reddit (seems to be the common denominator). If anybody else is having the same issue, Video DownloadHelper extension for Firefox works brilliantly.

**Comment by aliparlakci** [comment]
It used to download v.redd.it posts but it seems broken now. I will fix it as soon as possible. Thanks for the feedback.

**Comment by aliparlakci** [comment]
Check out the latest update on the master. It should be fixed now.

**Comment by memyselfandhai** [comment]
Works like a charm! Thanks again!
