### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by handgun50** [aliparlakci/bulk-downloader-for-reddit#55]
I'm using Termux on Android. I'm trying to authenticate Reddit by pasting link to browser, but authenticating failed maybe because I'm on Android, not on PC. Are there a solution to transfer the token without using that automatic authentication?

**Comment by aliparlakci** [comment]
Yes.

Start the script on a PC or Linux (basically a daily computer) and authenticate the script. It should create a config.json file at your home directory. To be more specific its directory is **`{HOME}\Bulk Downloader for Reddit\config.json`**

And you can put this file **next to** the script on your Android machine. It shouldn't ask for authentication again.

Let me know if you encounter an issue. I won't close the thread.

**Comment by handgun50** [comment]
I don't have pc ready with python, etc. Is it possible to give me the config.json with empty placeholder and copy manually the token?

**Comment by aliparlakci** [comment]
No it is not.
