### ISSUE TITLE
(Debian) (binary) GLIBC_2.25 not found

### ISSUE THREAD

**Issue by drandreaskrueger** [aliparlakci/bulk-downloader-for-reddit#58]
```
sudo apt-get install libc6
...
libc6 is already the newest version (2.24-11+deb9u4).
```

```
cd aliparlakci_bulk-downloader-for-reddit/bulk_downloader_for_reddit-1.6.4.2-linux
./bulk-downloader-for-reddit 
```

```
./bulk-downloader-for-reddit: 
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found 
(required by aliparlakci_bulk-downloader-for-reddit/bulk_downloader_for_reddit-1.6.4.2-linux/
libpython3.6m.so.1.0)
```

**Comment by aliparlakci** [comment]
Debian is not supported at the moment.

**Comment by drandreaskrueger** [comment]
> Debian is not supported 

not good, what a pity.

looks like I have to try to use windows then. Sigh.

**Comment by aliparlakci** [comment]
Sorry. I didn't want to be mean. I have been studying for university test
so I don't have the time to work on it.

**Comment by drandreaskrueger** [comment]
No worries. It's great that you are providing your software open source. No complaints. Sorry if I came across grumpy :-)

Best of luck with your university test !!

**Comment by aliparlakci** [comment]
Thanks a lot!
