### ISSUE TITLE
[BUG] Downloaded Videos have no image, only sound

### ISSUE THREAD

**Issue by Gramrock** [aliparlakci/bulk-downloader-for-reddit#584]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
Downloaded videos form subreddit have only audio, no video

## Command
```
python -m bdfr download ./lolo --subreddit MemeVideos --no-dupes -L 2 --file-scheme {REDDITOR}_{TITLE}_{POSTID}
```

## Environment (please complete the following information):
 - OS: [e.g. Windows 10]
 - Python version: [e.g. 3.9.4]

## Logs
```
Paste the log output here.
```

**Comment by Serene-Arc** [comment]
This is due to not having FFmpeg installed on your machine. The BDFR uses it to combine the audio and video streams. Install it from the FFmpeg site and this issue will be resolved.
