### ISSUE TITLE
line 571 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by drandreaskrueger** [aliparlakci/bulk-downloader-for-reddit#59]
```
python script.py 
  File "script.py", line 571
    print(f"\n({i+1}/{subsLenght}) – r/{submissions[i]['postSubreddit']}",
                                                                        ^
SyntaxError: invalid syntax
```

I had done this:

```
git clone https://github.com/aliparlakci/bulk-downloader-for-reddit aliparlakci_bulk-downloader-for-reddit
cd aliparlakci_bulk-downloader-for-reddit/
virtualenv -p python3 env
source env/bin/activate
python -m pip install -r requirements.txt

which python
.../aliparlakci_bulk-downloader-for-reddit/env/bin/python

python --version
Python 3.5.3

python script.py 
```

with this last commit

```
git log
commit 15a91e578496e1c07b5302606fab6061733eb1a1
Author: Ali <parlakciali@gmail.com>
Date:   Sun Feb 24 12:28:40 2019 +0300
    Fixed saving auth info problem
```

**Comment by aliparlakci** [comment]
You need to update your Python 3 to at least version 3.6.5. Format strings
came to Python with version 3.6.

**Comment by drandreaskrueger** [comment]
Thx for your superfast answer.

I am on Debian, and I don't want to break it, so I won't do that.

The official recommendation is "you don't actually need newer software"

https://wiki.debian.org/DontBreakDebian#Don.27t_suffer_from_Shiny_New_Stuff_Syndrome

Has your tool always been py3.6 or can I perhaps go back to an older commit?

Which commit did still work with py3.5 ?

**Comment by aliparlakci** [comment]
It has always been running on py3.6. Sorry :(

Have you tried using binaries?

**Comment by drandreaskrueger** [comment]
> It has always been running on py3.6. Sorry :(

what a pity ... Shiny New Stuff Syndrome, lol.

> Have you tried using binaries?

Yes, see other issue
