### ISSUE TITLE
SUBFOLDER

### ISSUE THREAD

**Issue by DarkSchythe0000** [aliparlakci/bulk-downloader-for-reddit#591]
In 1.10 version downloaded posts which has 2 or many images in them grouping in subfolder in subreddit folder by post title. I tried many ways but i can't done. Is there no subfolder feature or am i clumsy?

**Comment by Serene-Arc** [comment]
There is no option to group a gallery's images in a subfolder, no. You would be able to do this with bash scripts easily. The alternative would be using the folder scheme to put every image into a folder according to its submission ID, but this would result in a lot of folders with only one file.
