### ISSUE TITLE
[FEATURE] Bulk download flairs

### ISSUE THREAD

**Issue by HectateX** [aliparlakci/bulk-downloader-for-reddit#594]
- [ ] I am requesting a feature.
- [ ] I am running the latest version of BDfR
- [ ] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Maybe a way to bulk download flairs of certain subreddits?

**Comment by Serene-Arc** [comment]
This is already enabled by the `--search` option. Reddit lets you search for specific flairs.
