### ISSUE TITLE
Version 3.14.0 is labeled as a virus by BitDefender

### ISSUE THREAD

**Issue by DankMemeGuy** [aliparlakci/bulk-downloader-for-reddit#609]
Windows, v3.14.0. It's being labeled as a virus by BitDefdner. I don't know how to submit a false positive report, but if anyone else knows feel free to let me know or do it yourself. Thank you!

**Comment by Serene-Arc** [comment]
Uhhh okay, that's interesting. You are installing it as a python package right?

**Comment by DankMemeGuy** [comment]
> Uhhh okay, that's interesting. You are installing it as a python package right?

My apologies, just realized I submitted this bug on the wrong project. I will close.
