### ISSUE TITLE
Unraid User Scripts Errors

### ISSUE THREAD

**Issue by richowen** [aliparlakci/bulk-downloader-for-reddit#61]
Hi, I use the script on unraid with the userscripts plugin and theres some issues I've had to work around to get it to work.

- The automatic config gen doesnt really work on a remote client as the redirect is coded to localhost, so ive had to change the default config location and manually copied the reddit auth code from the end of the redirect url. 

`defaultConfigDirectory = Path("/mnt/user/***/Reddit/") / "config"`

- The userscripts output doesnt do UTF-8 so ive had to change your BAD_CHARS stripping to a GOOD_CHARS whitelist for filenames:
```
GOOD_CHARS = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
    
    if not all(x in string for x in GOOD_CHARS):
        for char in string:
            if not char in GOOD_CHARS:
                string = string.replace(char,"_")
```

Also had to replace the • (https://www.compart.com/en/unicode/U+2022) with a *
And the – (https://www.fileformat.info/info/unicode/char/2013/index.htm) with a -

Just letting you know, no idea if its worth doing anything about but just thought I'd let you know. 

Thanks for the script anyway.

**Comment by aliparlakci** [comment]
Thanks for your feedback, I appreciate it!

For your first issue, I proposed a solution on the FAQ section on the Readme page.

Can you tell me more about that userscript plugin? I have never heard it before, apparently.

**Comment by richowen** [comment]
yeh thats what i ended up doing, another lesson to just read the damn faq lol. 

its a small plugin to run scripts on a custom schedule 
[link](https://forums.unraid.net/topic/48286-plugin-ca-user-scripts/)
 it seems that the log output doesnt support emojis or non standard characters, the easiest fix would probably be to just ask the guy that makes the scripts if he can add support, but I thought id just let you know about it.
