### ISSUE TITLE
Is there a way to number downloaded files sequentially?

### ISSUE THREAD

**Issue by iammarxg** [aliparlakci/bulk-downloader-for-reddit#611]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
I'm trying to download a subreddit sorting by new, and would like to number every downloaded media sequentially.

I couldn't find an option in [Folder and File Name Schemes](https://github.com/aliparlakci/bulk-downloader-for-reddit#folder-and-file-name-schemes) to do that.

**Comment by Serene-Arc** [comment]
No, this isn't an option in the BDFR at this time. You can sort by creation time, which is set to the creation time of the post on Reddit.
