### ISSUE TITLE
[BUG]when i download from a subreddit where people use "reddit videos" only i get the sound and not the picture

### ISSUE THREAD

**Issue by kehayaa** [aliparlakci/bulk-downloader-for-reddit#612]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
when i download from a subreddit where people use "reddit videos" only i get the sound and not the picture

## Command
```
python -m bdfr download ./S:\PYTHON-FORMATIONS/to/output --subreddit publicfreakout-L 5
```

## Environment (please complete the following information):
 - OS: [e.g. Windows 10]
 - Python version: [e.g. 3.9.4]

## Logs
```
Paste the log output here.
```

**Comment by Serene-Arc** [comment]
Refer to discussions about this same topic. You need to install ffmpeg. Please look over other discussions before opening an issue

**Comment by instaloadererror** [comment]
> Refer to discussions about this same topic. You need to install ffmpeg. Please look over other discussions before opening an issue

What do I do if I've already installed ffmpeg and it's still saying the same thing?
![bdfr v redd it error](https://user-images.githubusercontent.com/67607076/213935868-3d5f946a-bf5d-4d37-a0f2-24fe55d1b225.png)

**Comment by Serene-Arc** [comment]
You cannot install ffmpeg through pip. What you have installed are the bindings for the ffmpeg program for python, but not the actual program. You need to go to the ffmpeg website and actually install it.
