### ISSUE TITLE
[FEATURE] Don't hard link images in the same directory

### ISSUE THREAD

**Issue by SierraNB** [aliparlakci/bulk-downloader-for-reddit#624]
Here's the problem i'm having, I download a few subreddit's top of this month every week or so to keep my database updated, I want duplicates to not be redownloaded but to be hard linked. 
Whenever I attempt to redownload a subreddit and there's overlap of posts i'm downloaded & have already downloaded, it proceeds to make tons of unnecessary hard links in the same directory (see below). There's no way to cover reposts between subreddits and eliminate unnecessary downloads/files from what I can tell. 

A flag to not hard link if the images are in the same directory would solve this use case which i'm sure is very common.

i.e I download /r/all top of all time once running this command  
`python3 -m bdfr download ./ --file-scheme {UPVOTES}_{REDDITOR}_{TITLE}_{POSTID} --subreddit all --search-existing --make-hard-links -L 10 --sort top --max-wait-time 15`
![Image](https://cdn.discordapp.com/attachments/855617702734725173/960957785573580810/Screenshot_20220405_103940.png)
Run the command again
![This is an image](https://cdn.discordapp.com/attachments/855617702734725173/960957768133656656/Screenshot_20220405_104118.png)
A hard link appears that isn't necessary

**Comment by Serene-Arc** [comment]
The de-duplication code that is included with the BDFR is not intended to be used for complicated scenarios and I'm not going to expand on them. The logic that goes into de-duplication is too complicated and is best left to other tools. Said tools have the capability to prune duplicate hard links in the same directory, if you want that.

Should be noted that what you want is not desirable behaviour for most people, assuming that they want an actual record of all posts. Deleting duplicate hard links will be akin to just not doing anything for those posts at all.
