### ISSUE TITLE
[FEATURE]: Print external links

### ISSUE THREAD

**Issue by chapmanjacobd** [aliparlakci/bulk-downloader-for-reddit#627]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
bdfr works great for image download, but sometimes I would like to download only the audio from a few subreddits which have mostly youtube links. 

Is there an option to pass flags/configuration to the youtube-dl module? 

Alternatively, it might be easier if `bdfr` can have an option to print all the candidate URLs that it finds then I can filter them and redirect to `yt-dlp` in a shell pipeline. Hypothetically, this might look like:

```
python -m bdfr download bdfr/ -S top --subreddit vintageobscura --print-url-only | grep youtube | xargs yt-dlp -f bestaudio
```

**Comment by chapmanjacobd** [comment]
I was able to get the functionality that I wanted by cloning the repo, pipenv install and making these modifications:

```py
class DownloadFactory:
    @staticmethod
    def pull_lever(url: str) -> Type[BaseDownloader]:
        sanitised_url = DownloadFactory.sanitise_url(url)
        if re.match(r".*/.*\.\w{3,4}(\?[\w;&=]*)?$", sanitised_url) and not DownloadFactory.is_web_resource(
            sanitised_url
        ):
            print(url)
            raise NotADownloadableLinkError()
        elif re.match(r"reddit\.com/r/", sanitised_url):
            return SelfPost
        else:
            print(url)
            raise NotADownloadableLinkError()
```

and

```py
        except errors.NotADownloadableLinkError as e:
-            logger.error(f'Could not download submission {submission.id}: {e}')
+            logger.info(f'Could not download submission {submission.id}: {e}')
```

then running:
```
python -m bdfr download bdfr/ --disable-module SelfPost -S top --subreddit vintageobscura | tee -a vintageobscura.txt
```

**Comment by chapmanjacobd** [comment]
I was able to get the functionality that I wanted by cloning the repo, pipenv install and making these modifications:

```py
class DownloadFactory:
    @staticmethod
    def pull_lever(url: str) -> Type[BaseDownloader]:
        sanitised_url = DownloadFactory.sanitise_url(url)
        if re.match(r".*/.*\.\w{3,4}(\?[\w;&=]*)?$", sanitised_url) and not DownloadFactory.is_web_resource(
            sanitised_url
        ):
            print(url)
            raise NotADownloadableLinkError()
        elif re.match(r"reddit\.com/r/", sanitised_url):
            return SelfPost
        else:
            print(url)
            raise NotADownloadableLinkError()
```

and

```py
        except errors.NotADownloadableLinkError as e:
-            logger.error(f'Could not download submission {submission.id}: {e}')
+            logger.info(f'Could not download submission {submission.id}: {e}')
```

then running:
```
python -m bdfr download bdfr/ --disable-module SelfPost -S top --subreddit vintageobscura | tee -a vintageobscura.txt
```

**Comment by chapmanjacobd** [comment]
Or maybe BDFR could follow a similar pattern with gallery-dl:

for example:

```
from gallery_dl import config, job

config.load()  # load default config files
config.set(("extractor",), "base-directory", "/tmp/")

# do the full download

for url in urls:
    job.DownloadJob(url).run()

# or just to get external links

url = 'https://old.reddit.com/r/crtgaming/'
job = DataJob(url)
urls = job.run()
```

I'm looking for an easy way to just get the extracted URLs. Maybe I'll have to use PRAW directly but BDFR feels easier. My modified script is still working fine but now I'm trying to incorporate it into my library program https://github.com/chapmanjacobd/lb/

**Comment by Serene-Arc** [comment]
So this is a bit ambiguous. Do you want all of the links that Reddit is linking to? Because then yes, I would say use `praw`. The part where you can get the links included in a post is trivial and only a few lines, and isn't really in the scope of the BDFR. If you really want, you can use the `RedditConnector` so that all of the setup is done and have it as a wrapper for praw.

However if you want the links once the pages have been parsed, that's more in the scope of this project. I can look into that if you wish.

**Comment by chapmanjacobd** [comment]
> RedditConnector

thanks that's helpful I'll look into that 

> once the pages have been parsed

I'm not sure I understand. I'm looking to get the links which match the following function where the url is printed

```py
def pull_lever(url: str) -> Type[BaseDownloader]:
        sanitised_url = DownloadFactory.sanitise_url(url)
        if re.match(r".*/.*\.\w{3,4}(\?[\w;&=]*)?$", sanitised_url) and not DownloadFactory.is_web_resource(
            sanitised_url
        ):
            print(url)
            raise NotADownloadableLinkError()
        elif re.match(r"reddit\.com/r/", sanitised_url):
            return SelfPost
        else:
            print(url)
            raise NotADownloadableLinkError()

```

But preferably the full metadata (score, title, etc) as an array of dictionaries.

**Comment by chapmanjacobd** [comment]
thanks for your expedited response. I have some direction now

**Comment by Serene-Arc** [comment]
The archive option saves everything to disk in a JSON format, though there are other options. But the point is that it collects all of that in an `ArchiveEntry` object. You can hook into that pretty easily and subvert the `download` function of the archiver. Sorry, we don't have the API documented but (hopefully) it's pretty easy to understand
