### ISSUE TITLE
[FEATURE]: links within links (SelfPosts)

### ISSUE THREAD

**Issue by chapmanjacobd** [aliparlakci/bulk-downloader-for-reddit#629]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Maybe this is beyond the scope of `bdfr` but there are a number of subreddits which are mostly SelfPost style but have links inside the post. The links inside the SelfPosts are the primary content of the subreddit. This style of data storage makes it difficult to archive everything or perform sophisticated and extensive analysis on the data :pushes-up-glasses:

I've previously done something like this in the past:

```py
import html
from urllib.parse import urlparse

import requests
import requests.utils
from bs4 import BeautifulSoup

def get_selfpost_links(url):
      .... api call to get the selfpost text ....
	  soup = BeautifulSoup(html.unescape(self_post_text), "lxml")
	  extlist = set()
	  
	  for a in soup.findAll("a", attrs={"href": True}):
	      if (
	          len(a["href"].strip()) > 1
	          and a["href"][0] != "#"
	          and "javascript:" not in a["href"].strip()
	          and "mailto:" not in a["href"].strip()
	          and "tel:" not in a["href"].strip()
	      ):
	          if "http" in a["href"].strip() or "https" in a["href"].strip():
	              if urlparse(link).netloc.lower() in urlparse(a["href"].strip()).netloc.lower():
	                  get_selfpost_links(a["href"]) # this is a recursive call
	              else:
	                  extlist.add(a["href"])
	          else:
	              print(link, file=sys.stderr)
	  
	  for el in extlist:
	      print(el)
```

one of the problems with this naive code (other than [soup](https://youtu.be/FAUnDDTz30k)) is that previously visited links are fetched more than once

It might be interesting to know if other people are also looking for this functionality and if the data transform operation could be improved and incorporated into `bdfr`

**Comment by Serene-Arc** [comment]
I think this feature is beyond the scope of the BDFR. The self-post module saves the text of the post to disk, and this feature could easily be implemented using `sed`, `awk`, `perl`, or even `grep`. There are any number of text processing tools that I think would be more useful and flexible than what could be implemented in the BDFR, especially since the use-case should really be wider than simple getting links.

**Comment by redredkrovy** [comment]
@chapmanjacobd Did you happen to find a good alternative to this?  I'm currently looking to download from a subreddit that only allow selfposts with the links in the text.

**Comment by chapmanjacobd** [comment]
Sure I made this: 

```
lb reddit-selftext -h
usage: library reddit-selftext DATABASE

    Extract URLs from reddit selftext from the reddit_posts table to the media table
```

part of https://github.com/chapmanjacobd/library

**Comment by chapmanjacobd** [comment]
Also if you need something more advanced, you can filter the links with the following subcommand:

    library links --local-html ./self-text.html

With this you can filter the links by the link text or the closest surrounding text:

    Filter Links:
      --path-include     path substrings for inclusion (all must match
      [VALUE ...]        to include)
      --text-include     link text substrings for inclusion (all must
      [VALUE ...]        match to include)
      --after-include    plain text substrings after URL for inclusion
      [VALUE ...]        (all must match to include)
      --before-include   plain text substrings before URL for inclusion
      [VALUE ...]        (all must match to include)
      --path-exclude     path substrings for exclusion (any must match
      [VALUE ...]        to exclude)
      --text-exclude     link text substrings for exclusion (any must
      [VALUE ...]        match to exclude)
      --after-exclude    plain text substrings after URL for exclusion
      [VALUE ...]        (any must match to exclude)
      --before-exclude   plain text substrings before URL for exclusion
      [VALUE ...]        (any must match to exclude)
      --strict-include   All include args must resolve true
      --strict-exclude   All exclude args must resolve true
      --case-sensitive   Filter with case sensitivity
      --no-url-decode    Skip URL-decode for --path-include/--path-
                         exclude

For example, you might do

    --text-include download

to match something like: [download](fake-url)

or

    --before-include listen

to match something like: listen [here](fake-url)

but if you're just piping the links to `lb download --safe --video` or yt-dlp it doesn't really matter much
