### ISSUE TITLE
[FEATURE]: min/max upvote filters

### ISSUE THREAD

**Issue by chapmanjacobd** [aliparlakci/bulk-downloader-for-reddit#630]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description

Similar to yt-dlp's `--min-views` and `--max-views` it would be nice if bdfr could filter out posts that had fewer than x upvotes (as well as downvotes or u/d-ratio).

```
bdfr --min-upvotes 500 'https://old.reddit.com/r/Damnthatsinteresting/top/?sort=top&t=week'
```

**Comment by Fakeaccount12312** [comment]
As a temporary fix until this feature is added, I start--file-scheme with {UPVOTES}-, then sort by name after its downloaded, select all files below/above the treshold + delete them, and remove the Upvotes from the file names with a mass renamer.
