### ISSUE TITLE
No sound in video

### ISSUE THREAD

**Issue by recvec** [aliparlakci/bulk-downloader-for-reddit#64]
There are no audio in downloaded video.
On some post I found the response, that Reddit serves the video and audio in separate tracks, so the app is unable to download a stream containing both, unless it re-encodes the video or something, which is much more work than downloading a file, and requieres significant more time/CPU.

**Comment by aliparlakci** [comment]
It will be an unnecessary load on CPU and will cost much more time as you say. Leaving it like that looks like a more reasonable choice.
