### ISSUE TITLE
GfyCat: download videos as mp4 instead of gif

### ISSUE THREAD

**Issue by mindjek07** [aliparlakci/bulk-downloader-for-reddit#646]
- [x] GfyCat: download videos as mp4 instead of gif

## Description

Use :  `https://api.gfycat.com/v1/gfycats/TallUnluckyInganue`

Out put : 
{
  "gfyItem": {
    "avgColor": "#141314",
    "content_urls": {
      "100pxGif": {
        "url": "https://thumbs.gfycat.com/TallUnluckyInganue-max-1mb.gif",
        "size": 887860,
        "width": 500,
        "height": 289
      },
      "largeGif": {
        "url": "https://thumbs.gfycat.com/TallUnluckyInganue-size_restricted.gif",
        "size": 3255662,
        "width": 620,
        "height": 359
      },
      "max1mbGif": {
        "url": "https://thumbs.gfycat.com/TallUnluckyInganue-max-1mb.gif",
        "size": 887860,
        "width": 500,
        "height": 289
      },
      "max2mbGif": {
        "url": "https://thumbs.gfycat.com/TallUnluckyInganue-small.gif",
        "size": 1776660,
        "width": 740,
        "height": 428
      },
      "max5mbGif": {
        "url": "https://thumbs.gfycat.com/TallUnluckyInganue-size_restricted.gif",
        "size": 3255662,
        "width": 620,
        "height": 359
      },
      "mobile": {
        "url": "https://thumbs.gfycat.com/TallUnluckyInganue-mobile.mp4",
        "size": 62992,
        "width": 640,
        "height": 370
      },
      "mobilePoster": {
        "url": "https://thumbs.gfycat.com/TallUnluckyInganue-mobile.jpg",
        "size": 8790,
        "width": 640,
        "height": 370
      },
      "mp4": {
        "url": "https://giant.gfycat.com/TallUnluckyInganue.mp4",
        "size": 495792,
        "width": 788,
        "height": 456
      },
      "webm": {
        "url": "https://giant.gfycat.com/TallUnluckyInganue.webm",
        "size": 68840,
        "width": 788,
        "height": 456
      },
      "webp": {
        "url": "https://thumbs.gfycat.com/TallUnluckyInganue.webp",
        "size": 69266,
        "width": 520,
        "height": 301
      }
    },
    "createDate": 1659082756,
    "description": "",
    "frameRate": 24.59893,
    "gatekeeper": 0,
    "gfyId": "tallunluckyinganue",
    "gfyName": "TallUnluckyInganue",
    "gfyNumber": 186652890,
    "gif100px": "https://thumbs.gfycat.com/TallUnluckyInganue-max-1mb.gif",
    "gifUrl": "https://thumbs.gfycat.com/TallUnluckyInganue-size_restricted.gif",
    "hasAudio": false,
    "hasTransparency": false,
    "height": 456,
    "languageCategories": [
      "curated",
      "trending"
    ],
    "likes": 7,
    "max1mbGif": "https://thumbs.gfycat.com/TallUnluckyInganue-max-1mb.gif",
    "max2mbGif": "https://thumbs.gfycat.com/TallUnluckyInganue-small.gif",
    "max5mbGif": "https://thumbs.gfycat.com/TallUnluckyInganue-size_restricted.gif",
    "miniPosterUrl": "https://thumbs.gfycat.com/TallUnluckyInganue-mobile.jpg",
    "miniUrl": "https://thumbs.gfycat.com/TallUnluckyInganue-mobile.mp4",
    "mobilePosterUrl": "https://thumbs.gfycat.com/TallUnluckyInganue-mobile.jpg",
    "mobileUrl": "https://thumbs.gfycat.com/TallUnluckyInganue-mobile.mp4",
    "mp4Size": 495792,
    "mp4Url": "https://giant.gfycat.com/TallUnluckyInganue.mp4",
    "nsfw": 0,
    "numFrames": 46,
    "posterUrl": "https://thumbs.gfycat.com/TallUnluckyInganue-poster.jpg",
    "published": 1,
    "tags": [
      "kiss",
      "kisses",
      "blonde",
      "ana de armas",
      "marilyn monroe",
      "sexy",
      "love",
      "flirt",
      "netflix",
      "hot"
    ],
    "thumb100PosterUrl": "https://thumbs.gfycat.com/TallUnluckyInganue-mobile.jpg",
    "title": "Blonde",
    "url": "https://gfycat.com/gifbrewery",
    "userData": {
      "followers": 540,
      "following": 1,
      "name": "Reaction GIFs",
      "profileImageUrl": "https://profiles.gfycat.com/90b80e23d5a0fcf53110a75f7f3dca27b68b3a0f9a692f9902d0297f8ead0a13.png",
      "profileUrl": "https://gfycat.com/featured/reactions",
      "subscription": 0,
      "url": "https://gfycat.com/featured/reactions",
      "username": "reactions",
      "verified": true,
      "views": 215390784
    },
    "userDisplayName": "Reaction GIFs",
    "username": "reactions",
    "userProfileImageUrl": "https://profiles.gfycat.com/90b80e23d5a0fcf53110a75f7f3dca27b68b3a0f9a692f9902d0297f8ead0a13.png",
    "views": 4844,
    "webmSize": 68840,
    "webmUrl": "https://giant.gfycat.com/TallUnluckyInganue.webm",
    "webpUrl": "https://thumbs.gfycat.com/TallUnluckyInganue.webp",
    "width": 788,
    "isSticker": false
  }
}

Gfycat does not limit the number of API calls made by third party developers.

**Comment by Serene-Arc** [comment]
Who do you mean by 'our', and what problem does this purport to solve in the BDFR?
