### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by saqibkhan2523** [aliparlakci/bulk-downloader-for-reddit#65]
I am using python source code on windows using this comman python script.py --directory .\\data --subreddit AnimalsBeingDerps --sort hot --limit 0

`GETTING POSTS
No matching submission was found`

**Comment by aliparlakci** [comment]
Looks like reddit has changed how "limit" option works. Just delete the `--limit 0` part and it will work as it should. I will be working on a fix as soon as possible.

**Comment by saqibkhan2523** [comment]
ok thanks
