### ISSUE TITLE
[BUG] --opts paramater doesn't seem to be included in the app?

### ISSUE THREAD

**Issue by MelanieTanaka** [aliparlakci/bulk-downloader-for-reddit#650]
- [X ] I am reporting a bug.
- [X ] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
Following the documentation, I am trying to include a "my_opts.yaml" file. When executing the command, the script complains that the parameter --opts doesn't exist.

## Command
```
py -m bdfr download W:\media\images\reddit --opts W:\media\images\reddit\reddit.yaml
Usage: python -m bdfr download [OPTIONS] DIRECTORY
Try 'python -m bdfr download --help' for help.

Error: No such option: --opts Did you mean --no-dupes?
```

## Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.10.6

## Logs
```
Logs not generated as the script does not execute past the on-screen error indicating --opts doesn't exist.
log_output.txt is not present in the AppData\Local\BDFR\bdfr directory.
```

**Comment by Serene-Arc** [comment]
Sorry, at the moment the main page of the repository is showing the documentation for the development branch. The `--opts` option is not released through PyPi at the moment. I've asked Ali to switch it back but I don't have the ability to do so myself.

If you want, you can install the development version through `pip install git+https://github.com/aliparlakci/bulk-downloader-for-reddit.git@development` to use the latest development version but there should be a release soon.
