### ISSUE TITLE
[FEATURE] Store the file hashes in a text file

### ISSUE THREAD

**Issue by iheartcsharp** [aliparlakci/bulk-downloader-for-reddit#651]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
So right now when you run the tool with the `--no-dupes --search-existing` flags it hashes all the files on each run. Instead there should be a log file with the hashes listed for the downloaded files. This way it doesn't have to generate hashes at startup.

I have about 30 subreddits I'm grabbing images from. So when I run the tool, it spends 5-10 minutes generating the hashes. If there was an `md5.log` file with the hashes of all the files it will save a lot of time. At startup, the tool will read in md5.log and only generate the MD5 hashes on files that aren't listed in the `md5.log` file.

Thanks

**Comment by Serene-Arc** [comment]
This won't be implemented. The `--no-dupes` option paired with the `--search-existing` is a bad solution to a problem that shouldn't exist. The way it finds duplicate files is the worst and most computation-heavy way, but the BDFR is a file downloader, not a duplicate finder. I wish I hadn't ever implemented this option tbh and I'm definitely not going to write a feature that results in *more* people using it

I recommend that you download with the BDFR and then use a third-party tool, such as `fdupes` or `rdfind` to remove or link duplicate files. That will be the fastest option over the long, medium, and even short term.
