### ISSUE TITLE
[BUG] if "-s" perimeter isn't capitalized a confusing error is given and results are sorted by hot "Source top is private and cannot be scraped"

### ISSUE THREAD

**Issue by Alden5** [aliparlakci/bulk-downloader-for-reddit#655]
If the "-S" perimeter if not capitalized the error 
"Source top is private and cannot be scraped" appears and results are downloaded from hot, it was super confusing as the error doesn't sound like an issue with formatting and other perimeters are allowed to be lowercase

**Comment by Serene-Arc** [comment]
This is because `-s` and `-S` mean different things. The first specifies a subreddit; the latter specifies a sort type. You can't capitalise or lowercase options as you please; they are case sensitive.
