### ISSUE TITLE
[BUG] Imgur redirection causing html page download

### ISSUE THREAD

**Issue by Soulsuck24** [aliparlakci/bulk-downloader-for-reddit#662]
## Description
Imgur redirection edge cases

**Comment by KylarZeppeli** [comment]
Just a heads up: I just downloaded 26,000 total images from 45 subreddits & only **two** of them downloaded as HTML, every other file was fine. That's 0.0000769% of the files.

**Comment by Soulsuck24** [comment]
Can you post the Reddit ID's of them so I have known ones to test against? I'm pretty sure I have it sorted out but all the ID's I have weren't causing issues before so I can't be 100% certain it's fixed.

**Comment by KylarZeppeli** [comment]
https://www.reddit.com/r/AdorableOnlyfans/comments/xho1pl/18_yo_post_daily_cute_pics_wanna_be_daddys_lil/
https://www.reddit.com/r/GWAustralia/comments/xflekg/is_that_a_fun_weekend_i_can_see/

xho1pl
xflekg
