### ISSUE TITLE
[FEATURE] import data request .csv

### ISSUE THREAD

**Issue by slormo** [aliparlakci/bulk-downloader-for-reddit#676]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
Reddit by default only searches the first 1000 saved/upvoted posts, but you can request a full list of everything ever upvoted/saved by requesting your data at [https://www.reddit.com/settings/data-request](https://www.reddit.com/settings/data-request). It would be neat if we could import the data as a .csv so we can archive every result.

**Comment by Serene-Arc** [comment]
You can already use the `--include-id-file` option to import a large number of IDs. This is the recommended way when requesting GPDR lists.
