### ISSUE TITLE
[FEATURE] Switch to skip txt posts

### ISSUE THREAD

**Issue by Wolfeman0101** [aliparlakci/bulk-downloader-for-reddit#686]
- [X] I am requesting a feature.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
I'd like to option to skip downloading text only posts.

**Comment by OMEGARAZER** [comment]
`--disable-module=SelfPost`

Will do this for you.

**Comment by Wolfeman0101** [comment]
Thanks I didn't realize that was what that did.  Close this.
