### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by noph34r** [aliparlakci/bulk-downloader-for-reddit#69]
is there a way to save the file without weird character like this "😋😏😂💦"??
also when i've download file, sometimes i delete some of it. but when i redownload it, it's downloaded again. is there a way to skip it (ie just download new ones)

**Comment by aliparlakci** [comment]
They are unicode characters and if a post's title contains them, it is not easy to filter them out. But you can implement the feature and I can merge with the project.
