### ISSUE TITLE
[BUG] Brotoli is broken

### ISSUE THREAD

**Issue by daynashaw** [aliparlakci/bulk-downloader-for-reddit#690]
Just a heads up that this bug is preventing BDFR from installing while using Python 3.11. Looks like there are already plans to have it fixed, but just wanted to open a tracking issue. 

https://github.com/google/brotli/issues/984

**Comment by Serene-Arc** [comment]
Is this one of our dependencies?

**Comment by OMEGARAZER** [comment]
Through yt-dlp, yes

**Comment by OMEGARAZER** [comment]
Looks like this has been resolved upstream.
