### ISSUE TITLE
Feature Request: Option to unsave items as they're downloaded

### ISSUE THREAD

**Issue by ErikLentz** [aliparlakci/bulk-downloader-for-reddit#70]
To keep my Reddit saves section clean, and to keep clear what has and hasn't been downloaded, I would love if it bulk-downloader could unsave items as it downloads them.

**Comment by Draxxx** [comment]
I'll second this. That'd be a great feature.

**Comment by DigiOhhh** [comment]
Third here!

**Comment by aliparlakci** [comment]
@Draxxx @DigiOhhh @ErikLentz 

Feature is live on the 1.8 version. Use the option --unsave

**Comment by DigiOhhh** [comment]
This is simply amazing, thank you so much!
Would it be possible to do the same thing with upvoted posts?
