### ISSUE TITLE
Headless Authenticating 

### ISSUE THREAD

**Issue by rustjunky** [aliparlakci/bulk-downloader-for-reddit#700]
I'm running BDFR on a headless Ubuntu box, there is no GUI available. I can authenticate using the Reddit API on another system, but I'm not sure how to feed the localhost URL that Reddit provides back to BDFR.

Are there instructions for BDFR specifically for headless operation?

**Comment by Serene-Arc** [comment]
You can authenticate on any system and copy over the OAUTH2 tokens that are added to the configuration file. These tokens, once valid, can work on any system.
