### ISSUE TITLE
[FEATURE] Pipx Support

### ISSUE THREAD

**Issue by mediatech15** [aliparlakci/bulk-downloader-for-reddit#702]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description
I would like support for installing via pipx. This should be easy as it is just a console script definition for setup.py

This would allow installation in a non-global manor or the need to not create a venv for the tool. Pipx handles venv/path/binary setup along with ability to specify the python version if your default is incompatible. I currently have 6 python versions and 3.7 is default for work purposes/personal development.

I may be able to submit a PR for this if needed.

**Comment by OMEGARAZER** [comment]
@mediatech15 I have a console entry point set up with some other changes I'm working on atm. As I don't use pipx I'm unsure if there's anything else that is needed on top of that though, are you aware of any by chance? If not I'll try my best to dig into pipx and test what I have.

**Comment by mediatech15** [comment]
@OMEGARAZER  This is their docs https://pypa.github.io/pipx/how-pipx-works/ 
There is a section for developing for pipx.
Not much more than what you mentioned. Idea of when that would be rolled in?

**Comment by OMEGARAZER** [comment]
Fully rolled in, not sure, but I'll dig into it this evening and test what I have.

If things go well I should be able to do a PR with just those changes.

**Comment by mediatech15** [comment]
Awesome If you make the PR and want an additional tester I can do that. Tag me in the PR.

**Comment by mediatech15** [comment]
@Serene-Arc Is there a planned release in the near future? I didn't see in the docs anything about typical release schedule so I'm assuming its as needed or when time permits?

**Comment by mediatech15** [comment]
Thanks all I successfully installed via pipx targeting development branch.

**Comment by Serene-Arc** [comment]
Excellent
