### ISSUE TITLE
Switch to automatic Black formatting

### ISSUE THREAD

**Issue by Serene-Arc** [aliparlakci/bulk-downloader-for-reddit#703]
This issue is to notify the stakeholders of this repository (namely the developers contributing) that I intend to switch this repository to automatic formatting with black.

This will standardise the formatting of the project and it can be integrated with tox and CI to do so automatically. 

Needless to say, this will introduce a large number of conflicts if there are PRs in progress since there's a high likelihood that many lines of code will change, I'm opening this and pinging people who will likely be impacted, namely @aliparlakci @OMEGARAZER  @chapmanjacobd @Soulsuck24.

For anyone else who is currently developing, hopefully you either see this or it won't be trouble. For those that I have pinged or otherwise have a stake in the current codebase remaining static, please leave comments below so we can organise a timeframe for me to introduce this new part of the workflow in a way that won't cause too much disruption for anyone.

**Comment by OMEGARAZER** [comment]
No issues here. Any specific settings for black you were looking to use? then can prep ahead of the switch.

**Comment by Serene-Arc** [comment]
Going to do default black with 120 character line lengths and isort as well with compatible settings. 

The black standard seems pretty unobjectionable.

**Comment by OMEGARAZER** [comment]
That's what I was figuring, just wanted to check.
