### ISSUE TITLE
Configure sorting of downloaded files.

### ISSUE THREAD

**Issue by evilmanimani** [aliparlakci/bulk-downloader-for-reddit#71]
Hey there, just had a couple suggestions/feature requests.

I'd like to be able define the directory structure for new downloads, i.e. perhaps based on file type. And also some sort of option to sort download files which retains the order in which they were saved, either by date saved (if that's something reddit exposes) at the start of the filename ( DD-MM-YYYY format) or just modifying the system modified date/created date to match that as well. If that's not possible, perhaps some sort of numeric ID, separate from the post ID that can be added to the start of the filename, that when sorted by will put the files in saved order.

I've been using some powershell scripts run afterwards as part of a batch script, but it's not working too well, in that it needs to copy everything to a new set of directories which doubles the amount of space used, and it appears the script only takes into account the contents of the destination folder to determine what has and hasn't already been downloaded. I tried using the --log option , thinking that might keep a log of what's been retrieved already, but I'm not sure what it's looking for in terms of arguments. I tried putting a directory path, the path with a filename with an without an extension (.json, and .txt) (tried both path options both enclosed in quotes as well), and a filename with and without ext without the path, and it doesn't seem to like any of those options; didn't have any luck finding any clarification in the docs either.

Cheers.

**Comment by Saortica** [comment]
Hey,
Just another tinkering user... but here are some ideas. I'm assuming you're on windows from your reference to powershell.

1) Order - this should be more or less maintained if you use the --sort new option. As each file is downloaded it will be timestamped in the subreddit order. Then you can just order your download folder by date in windows explorer/a file manager. Of course, this is thrown if some files fail to download during a sweep, for example if it is interrupted... and are then downloaded at a later date. So it's not perfect, but perhaps it's something. To my very limited knowledge it may not be possible for these kind of scripts/utilities to get date info on reddit posts, if you are after that kind of info.

2) Being able to move/delete files and not have them downloaded them again.
I've got a pretty workable .bat hack to get around this and not have to retain copies of the downloads. It involves creating empty files in place, and moving your downloads into a different location, which you essentially think of as your normal subreddit downloads. (Well it's just a little more complicated than that, but just see the remarks in the script to get the idea). The dummy files take up no space, are tucked away and are sufficient for bulk downloader to then skip the files next time.

***Use at your risk, involves moving files. Only use if you can understand the script and its potential dangers. Keep download folders well away from system files/other valuable data.***

Setup:
In your root download directory:
- make a subreddit.txt file, and enter the basic name of subreddits you wish to download, eg
pics
natureporn
wallpaper

- Have bulk downloader in this directory, or in your windows path

- make a new .bat file, and paste the following in:
```
set "Timestamp=%date:~7,2%-%date:~4,2%-%date:~10,4% %time:~0,2%_%time:~3,2%"  &REM Timestamp variable for discreet new files folder per session.

set "BaseFolder=C:\Reddit downloads"		&REM Enter your base bulk download folder here.
set "DataFolder=_Data"				&REM Enter your data folder here: where dummy files will be stored, under base folder.
set "NewfilesFolder=\_New %Timestamp%"		&REM This is created per subreddit folder. The \ is required here. Leave completely blank for root subreddit folder.

for /F "delims=;" %%S in (subreddits.txt) do (
Echo Checking %%S...
bulk-downloader-for-reddit -d "%BaseFolder%\%DataFolder%" --subreddit %%S --sort new --limit 200 --quit
robocopy "%BaseFolder%\%DataFolder%\%%S" "%BaseFolder%\%%S\_temp" /move /s /min:100 /MT:4	&REM Moves new downloads into temp folder.
robocopy "%BaseFolder%\%%S\_temp" "%BaseFolder%\%DataFolder%\%%S" /create /s /MT:4		&REM Copies back empty versions into data\subreddit folder.
robocopy "%BaseFolder%\%%S\_temp" "%BaseFolder%\%%S%NewfilesFolder%" /move /s /MT:4		&REM Moves new downloads from temp into Subreddit new files folder.
)

REM The Robocopy /MT: flag is the number of threads used by Robocopy. Change as desired
```
Replace the set folder variables with your base download folder (where the individual subreddit folders are stored), a data folder to be left alone, and a new files folder per subreddit (or leave it blank for subreddit root). Pay attention to whether backslashes are included or not per variable... else it will be thrown out.

Have fun!

Notes:
If you are confident, you can process existing downloads with this script. Just plonk them in the respective data\subreddit folder, and next time the subreddit is checked they will be processed, moved and duplicated. They don't need to be downloaded in that session.

Don't peek in the _temp folder while the files are being moved... this will likely interrupt the script.

3). Sorting files
Just create a .bat such as

```
mkdir _Videos
for /r %%x in (*.mp4) do move "%%x" _Videos
mkdir _Pics
for /r %%x in (*.jpg) do move "%%x" _Pics
for /r %%x in (*.png) do move "%%x" _Pics
```
And run it from the subreddit directories... or you could add something like it to the for loop in the above .bat taking into account the looped subreddit folder variables.

To the dev, I don't have experience with etiquette on the likes of github, so apologies if my workaround/bat suggestion is inappropriate here. Thanks for the utility, it's appreciated.

**Comment by evilmanimani** [comment]
Appreciate the effortpost, though I actually worked out a pretty simple solution with a different project: https://github.com/shadowmoose/RedditDownloader It keeps a manifest.sqlite file in the target folder to keep track of what's already been grabbed, then I just run robocopy in a batch file to sort the resultant files to different folders. Since it dumps it all into one folder by default (you can configure to create subreddit or user directories etc) I can just use robocopy instead of having to mess with powershell to search recursively through all the subfolders and flatten the directory structure.

I just made a scheduled task to run the following batch file every so often and it's been working pretty well so far.

```
@echo off
py -3 redditdownloader --interface.start_server=false
robocopy C:\RedditDownloader\download\ C:\reddit\pics\ *.jpg *.png *.gif /mov /copyall
robocopy C:\RedditDownloader\download\ C:\reddit\vids\ *.mp4 *.webm /mov /copyall
```

**Comment by Saortica** [comment]
I checked out RedditDownloader but for some reason didn't get it working. I'll have another crack, thanks for the headsup. In the meantime, my solution does work transparently after the 3 or four steps to setup, perhaps someone will find it useful when using bulk downloader. Good to have options, cheers!

**Comment by aliparlakci** [comment]
@evilmanimani @Saortica Sorry for coming late but university did not give me much freetime.

I actually implemented this feature in the develop branch and in couple of days I will be releasing a new version including feature.

So, stay tuned!

**Comment by aliparlakci** [comment]
@evilmanimani @Saortica 

Custom filename and folder structure is live on the 1.8 version.

Other feature requests will be worked on.
