### ISSUE TITLE
Couple feature requests.

### ISSUE THREAD

**Issue by chazragg** [aliparlakci/bulk-downloader-for-reddit#72]
after using this program for a while there is a couple of features I feel could be beneficial.

1) have the program change the date created meta tag to the time and date of the original post it downloads. this will give users more of a timeline of their upvoted posts when browsing through folders. might help them find a specific one easier.

2) change the "upvoted posts" options to be able to select certain subreddits you want this to apply to rather than just having it download everything.

**Comment by aliparlakci** [comment]
A year ago, when I was writing the code, I wanted to implement this feature but I could not find any "simple" solution for it. But I will research for it again.

Second feature sounds really good. I will try to implement it as soon as I have the time.

**Comment by Gerdoner** [comment]
Another great feature would be the possibility to download all reddit threads a user (me) has commented on

**Comment by aliparlakci** [comment]
I will work on those features.

**Comment by anup2050** [comment]
can you add a feature where u can download in bulk through links in a text or csv file (one link in one line)
