### ISSUE TITLE
[BUG] You cannot just write "user: me" in opts.yaml

### ISSUE THREAD

**Issue by bagar0x60** [aliparlakci/bulk-downloader-for-reddit#723]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

You can add the command line argument `--user me` but if you instead add `user: me` to opts.yaml and use it with `--opts ./opts.yaml` there will be the following error messages
```
[2022-12-18 12:40:28,111 - bdfr.connector - ERROR] - Could not find user m
[2022-12-18 12:40:28,324 - bdfr.connector - ERROR] - Could not find user e
```
So you have to set it like `user: [me]` in opts.yaml in order for the program to work correctly

## Command

```text
bdfr download ./ --opts ./opts.yaml
```

## Options
```yaml
authenticate: true
user: me
limit: 1
upvoted: true
```

## Environment (please complete the following information)

- OS: macOS
- Python version: 3.10.6

**Comment by OMEGARAZER** [comment]
Doing some testing on this I was able to work it out. You'll want to use

```yaml
authenticate: true
limit: 1
upvoted: true
user:
  - me
```

Seems any option that can take multiples needs to be formatted like that as that's how subreddits are formatted in yaml options.
