### ISSUE TITLE
[FEATURE] Prevention of redownloading posts(not deduplication) without md5 hashing

### ISSUE THREAD

**Issue by NolanSyKinsley** [aliparlakci/bulk-downloader-for-reddit#737]
- [ X] I am requesting a feature.
- [ X] I am running the latest version of BDfR
- [ X] I have read the [Opening an issue](../../README.md#configuration)

## Description

I like others wanted deduplication md5 hash storage but have checked the other closed issues and understand why you do not want to do it that way, and I completely agree, but I think I have a possible solution. I don't want deduplication hash storage, it wouldn't even really solve the problem I have. I want to prevent redownloading, it is the downloading that is the time consuming process that is the issue for me, I can deduplicate with tools later like you said if people posted multiple times in the same subreddit, or across subreddits, but as it stands every time I run the script it has to download the whole file to hash it to see if it is a duplicate. This takes a LONG time to do a whole subreddit to the max 1000 post limit. So why not use the postids? Either have a file that gets appended with the postid of every downloaded post that is held in the subreddit's folder to be checked against, or you can have it use the folder/file naming convention to extract the postids of the files in the subreddit folder and hold them in a json in memory to check against, that would be much less intensive than hashing the downloaded files and achieve most of the main goal that people are seeking with the currently available deduplication feature. 

This seems a little too obvious to have been looked over so there is probably some technical reason this won't work, but I can hope!

**Comment by Serene-Arc** [comment]
This already is a feature. There is an option `--exclude-id-file` that will exclude any posts with an ID in the file. Additionally, there are scripts in the `scripts/` folder to extract these IDs from any log file that the BDFR generates. This should do what you want.

**Comment by NolanSyKinsley** [comment]
I saw that there was that option but I did not know about that other script as it is not documented in the readme, seems like it should just be another launch option to store the post IDS rather than having to run a second script after each time you run BDFR to extract the IDs, would really streamline the process and be less confusing for users.

**Comment by NolanSyKinsley** [comment]
In the other replies you echoed the Unix philosophy, make one program do one thing well. Having manipulate log files to extract the data to store and then use later does not seem to fit that philosophy. Being able to do so organically through the command line at program runtime with an option such as --log-post-id-file would fit that philosophy much better.

Imagine a text editor that could load display files, but if you edited those files or made a new file, to save it told you to "manipulate its log files" to get the data you wanted.

**Comment by Serene-Arc** [comment]
I disagree. The goal of the BDFR is to download the files in a stateless manner. There is no central database or list that could change outside of the program. wget does not generate a list of downloads. 

Additionally, the BDFR is meant as a low level tool. The log files are created in a standardised manner with the full record of everything the BDFR has done, every link and post and site that it touches. This is the sole source of information on what was done in a run; besides the files, the BDFR doesn't leave any sign of a run behind, which means that the downloaded files can be moved or copied, even to an entirely different machine, and have a new instance of the BDFR run perfectly fine.

Getting the post IDs from the log file is only one of the functions that the scripts do. Another is displaying summaries or analysing the operation of the program. These functions are most easily applied to the log files; moving one of them into the core code of the BDFR doesn't make sense when the other parts are left as external code, but some of these clearly don't belong.

Ultimately, the aim of the BDFR is to be a stateless, base-level tool that can be run in any scenario, including cron jobs and other scripts,  with maximum freedom given to users. With the bash scripts, you can decide which errors to attempt again, or exclude from future runs. Just edit the scripts. Moving these into Python code would make them far less accessible.  So sorry but this feature is remaining closed.
