### ISSUE TITLE
Feature request: Save file directory, post location and amount

### ISSUE THREAD

**Issue by sky-burial** [aliparlakci/bulk-downloader-for-reddit#74]
Hey there. Just had a small suggestion. I am woefully ignorant about coding, so if there's a way of achieving what I'm requesting here without adding a feature, by all means let me know.

I usually always run the code with the same parameters. Always the same directory, always download 100 posts from the Saved list. I'd like to create a scheduled task so this happens daily, but I'd rather not type everything in every time. Again, I suspect this can be achieved without adding a feature, which I imagine is much more practical, so I'm willing to try anything to achieve this.

**Comment by aliparlakci** [comment]
You should check out Windows Scheduled Task.
