### ISSUE TITLE
Method to download files directly to the Google Drive with Google Collab.

### ISSUE THREAD

**Issue by Handyfff** [aliparlakci/bulk-downloader-for-reddit#754]
This is working for now. I spent few hours on it. I don't know anything about coding but this works out. Check it yourself and suggest any modifications.

https://github.com/Handyfff/Subreddit-to-Google-Drive-using-BDFR-and-Google-Collab

**Comment by Serene-Arc** [comment]
What is this supposed to be? Are you linking another project for us to include in our README? Are you just letting me know? Linking it in an issue isn't really the place, so I'm not sure what you want the outcome to be. Could you please elaborate?

**Comment by Handyfff** [comment]
You can include it in your readme. There was another method like this but it doesn't work anymore. I think it could help some people.
