### ISSUE TITLE
Connections seem to time out and downloads don't work

### ISSUE THREAD

**Issue by wAuner** [aliparlakci/bulk-downloader-for-reddit#78]
It seems that it  isn't working properly anymore. I've tested it multiple times on different machines with the same result. After usually a few successfully downloaded files it just freezes. I assume there is some error handling missing when the connection is refused or timed out. 
There is no information in the log files.

**Comment by aliparlakci** [comment]
Does it still occur in the latest release of v1
7.0? Can you check it?

**Comment by wAuner** [comment]
Seems to work now, good job.
Ever thought about using multiple threads and a queue to enable multiple parallel downloads?

**Comment by aliparlakci** [comment]
Yes I thought about that but that is a very challenging task for me and would take a lot of time. Multithread feature is at the bottom of other requested features right now but I will notify you if I implement it.
