### ISSUE TITLE
I'm a dumbass, send help

### ISSUE THREAD

**Issue by Necabo1** [aliparlakci/bulk-downloader-for-reddit#79]
I used this previously on another account for a long time, but now, since I changed accounts, I want the downloader to be on that one. The problem is, I don't remember how the hell I downloaded it, right now the problem is that I have no idea where to redirect the app, or am I even supposed to make an app myself? I want to use the .exe cuz it feels nicer and I'm more used to it, so any help what so ever would be welcome. I'm probably being an idiot and missing something important so don't yell at me thanks.

**Comment by aliparlakci** [comment]
Just delete the Bulk Downloader for Reddit folder in your home directory.
Then run the .exe

**Comment by Necabo1** [comment]
Ah, thanks, didn't cross my mind
