### ISSUE TITLE
NO AUDIO ON CLIPS?

### ISSUE THREAD

**Issue by domhnallfc** [aliparlakci/bulk-downloader-for-reddit#81]
This program works perfectly execpt NO AUDIO? on the clips, so all clips are useless without audio. Any chance this could be fixed? thanks!

**Comment by mountwebs** [comment]
See #64 As someone who just started using this, I found that very disappointing. Other than that it it is  a great script though!

**Comment by aliparlakci** [comment]
I will try to add that very feature in following days. But it will be optional.

**Comment by mountwebs** [comment]
@aliparlakci that would be great! I agree that it should be optional.

**Comment by Neka78** [comment]
Would be awesome if we had the sound of the videos.. that's a powerfull tool that you did.

**Comment by aliparlakci** [comment]
@mountwebs @domhnallfc @Neka78 

The feature is live on the develop branch! And the program is still as snappy as it was.

I will soon release a new version including this feature.

**Comment by mountwebs** [comment]
Great. Thank you for adding this @aliparlakci !

**Comment by aliparlakci** [comment]
Bug is fixed on the 1.8 version. But see ffmpeg section in the README.
