### ISSUE TITLE
filenames too long

### ISSUE THREAD

**Issue by grokskookum** [aliparlakci/bulk-downloader-for-reddit#83]
I saw errors about files not being created due to filename length, do you know of any workaround?
I am just running normal btrfs, so the filename is I think limited to 255 characters.

**Comment by aliparlakci** [comment]
Download your files in a directory woth a short address such as
"C:/posts/". If the directory address is too long, the filename error will
occur even if the filename itself is not that long.

**Comment by grokskookum** [comment]
This is a bug. if the reddit poster uses stupid ansii graphic characters then the filename becomes way too long no matter what the local directory name is. the filename should simply be truncated if beyond 255 characters.

**Comment by aliparlakci** [comment]
It actually truncates the file name if it is over 200 characters long.

**Comment by cpalazzo** [comment]
Any emoji will trigger this.  Script should just handle invalid characters in title gracefully and continue to download content, as grokskookum says.

UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f618' in position 50: character maps to <undefined>

**Comment by cpalazzo** [comment]
Any emoji will trigger this. Script should just handle invalid characters in title gracefully and continue to download content, as grokskookum says.

UnicodeEncodeError: 'charmap' codec can't encode character \ud83e\udd37 in position 50: character maps to <undefined>

**Comment by krummrey** [comment]
> ERROR:root:OSError
> Traceback (most recent call last):
>   File "script.py", line 351, in <module>
>     main()
>   File "script.py", line 337, in main
>     else: download(posts)
>   File "script.py", line 140, in download
>     if isPostExists(details,directory):
>   File "script.py", line 79, in isPostExists
>     if path.exists():
>   File "/usr/lib/python3.6/pathlib.py", line 1336, in exists
>     self.stat()
>   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
>     return self._accessor.stat(self)
>   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
>     return strfunc(str(pathobj), *args)
> OSError: [Errno 36] File name too long: 
>

**Comment by koeningyou** [comment]
Hi,

I'm getting the same error;

`Traceback (most recent call last):
  File "script.py", line 360, in <module>
    main()
  File "script.py", line 345, in main
    download(posts)
  File "script.py", line 140, in download
    if isPostExists(details, directory):
  File "script.py", line 79, in isPostExists
    if path.exists():
  File "/usr/lib/python3.8/pathlib.py", line 1388, in exists
    self.stat()
  File "/usr/lib/python3.8/pathlib.py", line 1194, in stat
    return self._accessor.stat(self)
OSError: [Errno 36] File name too long: 
`

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by Serene-Arc** [comment]
This has been fixed in v2 of the project
