### ISSUE TITLE
Gfycat fail to download (exception thrown)

### ISSUE THREAD

**Issue by DennisPing** [aliparlakci/bulk-downloader-for-reddit#85]
### System
Mac OS
Python 3.7.7
Script version 1.6.5

### Issue
Gfycat links fail to download. The script throws an exception, and the script continues until finish.

`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### Example
I want to download the top 20 from a subreddit. There are 10 imgur links, 8 reddit image links, and 2 gfycat links. There are no non-supported links. Only the 2 gfycat links fail to download.

**Comment by aliparlakci** [comment]
It is solve in the latest release.
