### ISSUE TITLE
Possible to skip video files?

### ISSUE THREAD

**Issue by hostmanager1028** [aliparlakci/bulk-downloader-for-reddit#89]
Looking for pictures and videos are taking up a lot of bandwidth. Is it possible to skip video/mp4 files? I can use the download later option and sort them but it's tedious. Thanks a ton!

**Comment by aliparlakci** [comment]
I will implement the feature on the upcoming update. Thanks for feedback!

**Comment by aliparlakci** [comment]
Skipping domains feature is added on the latest release. Skipping certain file types feature will be added soon.

**Comment by aliparlakci** [comment]
The feature is live on v1.9.0
