### ISSUE TITLE
Gfycat NSFW download error: NotADownloadableLinkError: Could not read the page source. Gfycat now using redgifs for NSFW submissions?

### ISSUE THREAD

**Issue by ymgenesis** [aliparlakci/bulk-downloader-for-reddit#90]
I've updated my script to the latest pull that fixes the previous Gfycat error:
`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I now see a new exception with Gfycat posts.

**System**

Mac OS 10.14.6 & Ubuntu Server 16.04
Both Python 3.6.5

**Issue**

Most NSFW Gfycat posts return the following new error:

`NotADownloadableLinkError: Could not read the page source`
or
`HTTPError: HTTP Error 404: Not Found`

Maybe they are just both similar results of Gfycat removing NSFW posts from their main domain. I guess it's an issue now that gfycat is [migrating NSFW content to redgifs](https://www.reddit.com/r/gfycat/comments/e9ryd3/nsfwadult_content_announcement/)? Seems they're [blocking NSFW submissions to the gfycat domain](https://www.reddit.com/r/gfycat/comments/gjq34k/migration_update/). 

I've tested gfycat downloads on non-nsfw subs, and they seem to download fine. Also, some NSFW Gfycat posts seem to download fine (maybe older ones which haven't be purged yet?). 

redgifs.com submissions do show up in log file POSTS.json (not FAILED.json, as the mentioned NSFW Gfycat submissions do), but their PostType shows as null, and upon checking they don't actually download or reach the console at all. 

**Example**

[Here's a censored pastebin (SFW)](https://pastebin.com/8s0fejx1) I made with an example of what I'm talking about. Includes CONSOLE_LOG.txt, FAILED.json, and POSTS.json. Offending errors are pointed out.

Any plans to add redgifs.com support? It seems to be crawled/indexed and shows up in POSTS.json, but not downloaded. I guess it just needs some entries in src/. I know NSFW is controversial at times, it's all legal NSFW stuff we're talking about here, but I imagine it's one of the main ways this script is used.

**Pull Request**

Made [this pull reques](https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/92#issue-422306880)t after digging around myself. Not too familiar with Python, but my changes work fine for me, and adds redgifs support. **Important to note** that most NSFW Gfycat posts will still throw the above exceptions, as they are no longer allowed and are being removed from Gfycat's domain. As users switch over to redgifs, these errors will go away.

**Comment by ymgenesis** [comment]
Added [this pull request](https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/92#issue-422306880), but for the life of me can't figure out how to link it to this issue, unless only the maintainer can do that. Would make sense.

The commits on my fork changes three files to add redgifs.com support, and also includes the one-line change pull request in [this issue affecting gfycat](https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/85#issue-608780688).

**Comment by alphonso-a** [comment]
can this be put in an .exe fomat or no?

**Comment by ymgenesis** [comment]
> can this be put in an .exe fomat or no?

I don't have the knowledge to add my changes to an .exe binary, sorry! If the maintainer sees my pull request, maybe they can add it in and make a new release for Windows.

**Comment by alphonso-a** [comment]
okay, thanks for the response.

**Comment by aliparlakci** [comment]
no worries, I am here :)

**Comment by aliparlakci** [comment]
Can you check the latest version?

**Comment by ymgenesis** [comment]
> Can you check the latest version?

The redgifs support works great! Thanks for doing that. Every now and again there are still Gfycat posts that fail to download:
`HTTPError: HTTP Error 404: Not Found`
But I don't think that's an error relating to your script. I think it's Gfycat removing the content, so it's no longer available to download, and spits out a 404 not found (as I mentioned in my issue, here).

But in terms of the issue, I'd consider this one solved as long as people realize that some Gfycat nsfw posts are being removed and therefor undownloadeable.

**Comment by aliparlakci** [comment]
I can maybe add a custom error to that message. Thanks for the feedback!
