### ISSUE TITLE
can I download all the comments of a post?

### ISSUE THREAD

**Issue by Caiuzx** [aliparlakci/bulk-downloader-for-reddit#98]
I have seen that it only downloads the first post and not all the comments - is it possible to download all the comments of a post? NOT by a user - but all comments from a post 

ps: it would be convenient for me to download all the comments from my SAVED posts
thanks for your work.

**Comment by aliparlakci** [comment]
I thought about that but at the time I could not figured how should I store the comments. Do you have any suggestions?

**Comment by Caiuzx** [comment]
the initial post is downloaded in text file.
This is very nice, even the images are separate.
Why don't you let the program download the various comments in txt text files with the suffix decided by us?
for example post_name_comment_1.txt
nome_post_comment_2.txt
nome_post_comment_3.txt
?
it's just an idea. I'm not a programmer and I don't know how to do it.
at the end the program only downloads text files which are 1kb. If I have a thousand it's ONLY 1 MB.

**Comment by aliparlakci** [comment]
But there is a certain structure of comments such as replys. Do you really
want all the comments in one folder without any context of which one is an
answer to which one?

**Comment by Caiuzx** [comment]
Yes, it's true. but the ones I want to download are comments from the posts, because they have a context that interests me!
yes you are right, but for example the comments of talbetopgamedesign interest me and are not without answer.
The right way, if you can implement it, is to select with a number or condition yes | no if one wants to download all the comments of a post that interests him.
For example, I would NEVER download, as you say, the comments of the epicgames FREE games :)

**Comment by aliparlakci** [comment]
At the time, I don't have any intentions of implementing such feature because of the way I see the Bulk Downloader for Reddit's philosophy.

However, it might be implemented in the future. Stay tuned!

**Comment by dessalines** [comment]
This is really important for education subs, the comments are where the real content of the sub is.

**Comment by kqvanity** [comment]
@aliparlakci Will this feature ever be implemented?
